// physdump exports what the browser needs to run the car physics: per track, the slice
// of initialised game memory the physics reads ($1B000..$30000 -- car state, the loaded
// section arrays, the sin table and the piece shapes), plus a golden per-frame state
// trace generated by the verified Go physics (package physics). The JS port self-checks
// against the trace in the browser, keeping the in-browser sim coordinate-exact.
//
// Usage: physdump game.dec.bin [-out dir]
package main

import (
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"stuntcar/extract/physics"
	"retroreverse.com/tools/m68k"
)

const (
	base     = 0xE700
	sentinel = 0xFFFFFE
	stackTop = 0x300000
	memLo    = 0x1B000
	memSplit = 0x1C900 // per-track contiguous block (car state + section arrays) ends here
	ctrlLo   = 0x1CA1A // per-track control bytes (section count, finish idx, track id $1CA33)
	ctrlHi   = 0x1CA42 // ... up to the static sin table
	memHi    = 0x30000
)

type flatBus struct{ m []byte }

func (b *flatBus) Read(a uint32) byte     { return b.m[a&0xFFFFFF] }
func (b *flatBus) Write(a uint32, v byte) { b.m[a&0xFFFFFF] = v }

func call(bus *flatBus, c *m68k.CPU, pc uint32, regs map[int]uint32) {
	c.A[7] = stackTop - 4
	r := uint32(sentinel)
	bus.Write(c.A[7], byte(r>>24))
	bus.Write(c.A[7]+1, byte(r>>16))
	bus.Write(c.A[7]+2, byte(r>>8))
	bus.Write(c.A[7]+3, byte(r))
	for reg, v := range regs {
		c.D[reg] = v
	}
	c.PC = pc
	for steps := 0; c.PC != sentinel; steps++ {
		if c.Halted || steps > 50_000_000 {
			fmt.Printf("halt/cap at $%X\n", c.PC)
			os.Exit(1)
		}
		c.Step()
	}
}

var names = []string{"little-ramp", "stepping-stones", "hump-back", "big-ramp",
	"ski-jump", "draw-bridge", "high-jump", "roller-coaster"}

func main() {
	out := flag.String("out", "../../site/public/stuntcar/phys", "output dir")
	flag.Parse()
	img, err := os.ReadFile(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, "physdump:", err)
		os.Exit(1)
	}
	os.MkdirAll(*out, 0o755)

	for id := 0; id < 8; id++ {
		mem := initTrack(img, id)
		// per-track init = the array block + the small control region (so $1CA1A/$1CA33
		// etc. are right per track); the static data (sin table + shapes) is written once.
		perTrack := make([]byte, 0, (memSplit-memLo)+(ctrlHi-ctrlLo))
		perTrack = append(perTrack, mem[memLo:memSplit]...)
		perTrack = append(perTrack, mem[ctrlLo:ctrlHi]...)
		if err := os.WriteFile(filepath.Join(*out, fmt.Sprintf("%d.bin", id)), perTrack, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if id == 0 {
			os.WriteFile(filepath.Join(*out, "static.bin"), mem[memSplit:memHi], 0o644)
		}
		// golden trace from the verified Go physics.
		trace := goldenTrace(img, mem)
		b, _ := json.Marshal(trace)
		os.WriteFile(filepath.Join(*out, fmt.Sprintf("%d.trace.json", id)), b, 0o644)
		fmt.Printf("track %d (%s): %d.bin (%d bytes) + trace (%d frames)\n",
			id, names[id], id, len(perTrack), len(trace.Frames))
	}
	fmt.Printf("static.bin: %d KB (sin table + piece shapes, shared)\n", (memHi-memSplit)/1024)
}

// initTrack loads a track and places the car (the real setup chain on the m68k core),
// returning the full 24-bit memory.
func initTrack(img []byte, id int) []byte {
	bus := &flatBus{m: make([]byte, 1<<24)}
	copy(bus.m[base:], img)
	c := m68k.NewCPU(bus)
	bus.m[0x1CA33] = byte(id)
	call(bus, c, 0x5AE46, map[int]uint32{1: uint32(id)})
	call(bus, c, 0x64304, nil)
	call(bus, c, 0x5A794, nil)
	call(bus, c, 0x696FC, nil)
	// place the car (gear 1) and arm the race state for normal driving.
	g := uint32(1 & 3)
	bus.m[0x1BCD8] = bus.m[0x60552+g]
	bus.m[0x1BCE0] = bus.m[0x60556+g]
	bus.m[0x1BCE6] = bus.m[0x6055A+g]
	bus.m[0x1BCDC], bus.m[0x1BCDD] = 0x03, 0xF0
	bus.m[0x1BC42], bus.m[0x1BC43] = 0x07, 0x00
	bus.m[0x1BB68], bus.m[0x1BB57], bus.m[0x1BB72] = 0x80, 1, 0x80
	bus.m[0x1BBDF], bus.m[0x1BB46], bus.m[0x63EE0], bus.m[0x620B6] = 0, 0, 5, 5
	return bus.m
}

type trace struct {
	Frames [][]int32 `json:"frames"` // per frame: [drive, posX, posY, posZ, roll, yaw, pit, velX, velY, velZ]
}

// goldenTrace runs the Go physics with a scripted throttle and records the state, for the
// JS port to reproduce.
func goldenTrace(img, mem []byte) trace {
	gm := physics.New(img)
	copy(gm.B, mem)
	gm.B[0x64AEC], gm.B[0x64AED], gm.B[0x64AEE], gm.B[0x64AEF] = 0x9C, 0xED, 0xCD, 0x02
	var t trace
	for f := 0; f < 240; f++ {
		drive := int16(0x2800) // steady throttle
		gm.SetW(physics.Drive, drive)
		gm.Frame6185C()
		t.Frames = append(t.Frames, []int32{
			int32(drive), gm.L(physics.PosX), gm.L(physics.PosY), gm.L(physics.PosZ),
			int32(gm.W(physics.Roll)), int32(gm.W(physics.Yaw)), int32(gm.W(physics.Pit)),
			int32(gm.W(physics.VelX)), int32(gm.W(physics.VelY)), int32(gm.W(physics.VelZ)),
		})
	}
	return t
}

var _ = binary.LittleEndian
