// Generated by tools/browser/state/generate.py. Explicit format v1 fields.
#pragma once
#include "../../../../browser/state/translated.h"
inline void stateFields(rrstate::Archive&a,allegrex_Inst&v){a(v.Addr,v.Len,v.Mnem,v.Text,v.Flow,v.Target,v.HasTarget,v.HasDelay);}
inline void stateFields(rrstate::Archive&a,allegrex_loadSlot&v){a(v.reg,v.val);}
inline void stateFields(rrstate::Archive&a,allegrex_CPU&v){a(v.R,v.out,v.HI,v.LO,v.PC,v.nextPC,v.COP0,v.F,v.FCC,v.V,v.VfpuCtrl,v.Halted,v.HaltReason,v.Steps,v.curPC,v.ld,v.delaySlot,v.pendingDelay,v.branchAddr,v.nullifyNext);}
inline void stateFields(rrstate::Archive&a,allegrex_CPUState&v){a(v.R,v.Out,v.HI,v.LO,v.PC,v.NextPC,v.COP0,v.F,v.FCC,v.V,v.VfpuCtrl,v.Halted,v.HaltReason,v.Steps,v.CurPC,v.LdReg,v.LdVal,v.DelaySlot,v.PendingDelay,v.BranchAddr,v.NullifyNext);}
inline void stateFields(rrstate::Archive&a,psp_PixelEvent&v){a(v.Drawn,v.ScissorReject,v.AlphaReject,v.StencilReject,v.ZReject,v.MaskReject,v.R,v.G,v.B,v.A);}
inline void stateFields(rrstate::Archive&a,psp_MemRegion&v){a(v.Name,v.Base,v.Size);}
inline void stateFields(rrstate::Archive&a,pend&v){a(v.si,v.off);}
inline void stateFields(rrstate::Archive&a,psp_Segment&v){a(v.VAddr,v.FileOff,v.Data,v.MemSize);}
inline void stateFields(rrstate::Archive&a,psp_Import&v){a(v.Library,v.NIDs,v.StubAddr);}
inline void stateFields(rrstate::Archive&a,psp_reloc&v){a(v.offset,v.info);}
inline void stateFields(rrstate::Archive&a,psp_Module&v){a(v.Name,v.Type,v.EntryPC,v.GP,v.Segments,v.Imports,v.relocs,v.Encrypted,v.Tag);}
inline void stateFields(rrstate::Archive&a,psp_GeList&v){a(v.Start,v.Words);}
inline void stateFields(rrstate::Archive&a,psp_geState&v){a(v.fbLow,v.fbHigh,v.fbStride,v.fbFmt,v.base,v.vaddr,v.iaddr,v.offAddr,v.vtype,v.patchDivU,v.patchDivV,v.lightOn,v.matDiffuse,v.matEmissive,v.ambientCol,v.lightEnable,v.lightType,v.lightPos,v.lightDiff,v.vpXS,v.vpYS,v.vpZS,v.vpXC,v.vpYC,v.vpZC,v.offX,v.offY,v.world,v.view,v.proj,v.worldIdx,v.viewIdx,v.projIdx,v.matColor,v.clearOn,v.texEnable,v.texAddrN,v.texStrideN,v.texWN,v.texHN,v.texMaxLvl,v.texLodMode,v.texLodBias,v.texAddr,v.texStride,v.texW,v.texH,v.texFmt,v.texSwizzle,v.texScaleU,v.texScaleV,v.texOffU,v.texOffV,v.clutAddr,v.clutFmt,v.clut,v.blendOn,v.blendSrc,v.blendDst,v.blendEq,v.blendFixA,v.blendFixB,v.alphaTestOn,v.alphaFunc,v.alphaRef,v.alphaTestMask,v.texMapMode,v.texProjSrc,v.texWrapU,v.texWrapV,v.texLinear,v.texFunc,v.texUseA,v.texDouble,v.texEnvCol,v.texMtx,v.texMtxIdx,v.scX0,v.scY0,v.scX1,v.scY1,v.maskRGB,v.maskA,v.zLow,v.zHigh,v.zStride,v.zTestOn,v.zFunc,v.zNoWrite,v.clearDepth,v.cullOn,v.cullFace,v.stencilOn,v.stFunc,v.stRef,v.stMask,v.stSFail,v.stZFail,v.stZPass,v.fogOn,v.fogEnd,v.fogScale,v.fogColor,v.trSrc,v.trDst,v.trSrcStride,v.trDstStride,v.trSrcX,v.trSrcY,v.trDstX,v.trDstY,v.trW,v.trH);}
inline void stateFields(rrstate::Archive&a,psp_vert&v){a(v.x,v.y,v.z,v.u,v.v,v.r,v.g,v.b,v.a,v.cx,v.cy,v.cz,v.cw,v.invW,v.fog,v.clip);}
inline void stateFields(rrstate::Archive&a,psp_vertexLayout&v){a(v.tfmt,v.cfmt,v.nfmt,v.pfmt,v.idxFmt,v.offTex,v.offCol,v.offNrm,v.offPos,v.stride,v.through);}
inline void stateFields(rrstate::Archive&a,psp_geWire&v){a(v.FbLow,v.FbHigh,v.FbStride,v.FbFmt,v.Base,v.Vaddr,v.Iaddr,v.OffAddr,v.Vtype,v.PatchDivU,v.PatchDivV,v.LightOn,v.MatDiffuse,v.MatEmissive,v.AmbientCol,v.LightEnable,v.LightType,v.LightPos,v.LightDiff,v.VpXS,v.VpYS,v.VpZS,v.VpXC,v.VpYC,v.VpZC,v.OffX,v.OffY,v.World,v.View,v.Proj,v.WorldIdx,v.ViewIdx,v.ProjIdx,v.MatColor,v.ClearOn,v.TexEnable,v.TexAddrN,v.TexStrideN,v.TexWN,v.TexHN,v.TexMaxLvl,v.TexLodMode,v.TexLodBias,v.TexAddr,v.TexStride,v.TexW,v.TexH,v.TexFmt,v.TexSwizzle,v.TexScaleU,v.TexScaleV,v.TexOffU,v.TexOffV,v.ClutAddr,v.ClutFmt,v.Clut,v.BlendOn,v.BlendSrc,v.BlendDst,v.BlendEq,v.BlendFixA,v.BlendFixB,v.AlphaTestOn,v.AlphaFunc,v.AlphaRef,v.AlphaTestMask,v.TexMapMode,v.TexProjSrc,v.TexWrapU,v.TexWrapV,v.TexLinear,v.TexFunc,v.TexUseA,v.TexDouble,v.TexEnvCol,v.TexMtx,v.TexMtxIdx,v.ScX0,v.ScY0,v.ScX1,v.ScY1,v.MaskRGB,v.MaskA,v.ZLow,v.ZHigh,v.ZStride,v.ZTestOn,v.ZFunc,v.ZNoWrite,v.ClearDepth,v.CullOn,v.CullFace,v.StencilOn,v.StFunc,v.StRef,v.StMask,v.StSFail,v.StZFail,v.StZPass,v.FogOn,v.FogEnd,v.FogScale,v.FogColor,v.TrSrc,v.TrDst,v.TrSrcStride,v.TrDstStride,v.TrSrcX,v.TrSrcY,v.TrDstX,v.TrDstY,v.TrW,v.TrH);}
inline void stateFields(rrstate::Archive&a,psp_Image&v){a(v.Volume);}
inline void stateFields(rrstate::Archive&a,psp_subIntr&v){a(v.intno,v.subno,v.handler,v.arg,v.enabled);}
inline void stateFields(rrstate::Archive&a,psp_Entry&v){a(v.Name,v.Path,v.IsDir,v.Size,v.Block);}
inline void stateFields(rrstate::Archive&a,psp_ioFile&v){a(v.path,v.ent,v.pos,v.async,v.hasAsync,v.dir,v.dirPos);}
inline void stateFields(rrstate::Archive&a,psp_Volume&v){a(v.System,v.Name,v.rootLBA,v.rootSize);}
inline void stateFields(rrstate::Archive&a,psp_syscall&v){a(v.name);}
inline void stateFields(rrstate::Archive&a,psp_kobject&v){a(v.kind,v.name,v.entry,v.addr,v.size,v.used,v.bits,v.count,v.priority,v.stackTop,v.tstate,v.ctx,v.waitEv,v.waitBits,v.waitMode,v.waitOutPtr,v.waitSema,v.waitNeed,v.wakeVblank);}
inline void stateFields(rrstate::Archive&a,psp_PadEvent&v){a(v.AtVblank,v.Buttons);}
inline void stateFields(rrstate::Archive&a,psp_mpegState&v){a(v.Handle,v.Ringbuf,v.Packets,v.In,v.Cb,v.CbArg,v.Data,v.Pts,v.FedTotal);}
inline void stateFields(rrstate::Archive&a,psp_geCounters&v){a(v.lists,v.prims,v.verts,v.frags,v.zKilled,v.aKilled,v.sKilled,v.scissored,v.xfers);}
inline void stateFields(rrstate::Archive&a,psp_ProfileBucket&v){a(v.Name,v.Millis,v.Count);}
inline void stateFields(rrstate::Archive&a,psp_ProfileCounter&v){a(v.Name,v.Value);}
inline void stateFields(rrstate::Archive&a,psp_FrameProfile&v){a(v.TotalMs,v.Buckets,v.Counters);}
inline void stateFields(rrstate::Archive&a,psp_profState&v){a(v.ns,v.count,v.runStart,v.inRun,v.frameNs,v.base,v.baseInstr,v.gen,v.last,v.has);}
inline void stateFields(rrstate::Archive&a,psp_Machine&v){a(v.vram,v.scratch,v.CPU,v.io,v.syscalls,v.nextSyscall,v.handles,v.nextHandle,v.heapPtr,v.heapEnd,v.threadEntry,v.current,v.doneReason,v.subIntrs,v.vblanks,v.pad,v.padPrev,v.padScript,v.savedataStatus,v.volatileLocked,v.mpeg,v.atrac,v.nextAtrac,v.files,v.nextFd,v.audioCh,v.SyscallCalls,v.tty,v.fbAddr,v.fbWidth,v.fbFormat,v.geSt,v.geLimit,v.geCount,v.imageHash,v.WatchLo,v.WatchHi,v.RWatchLo,v.RWatchHi,v.StopRequested,v.geCnt,v.Halted,v.HaltReason);}
inline void stateFields(rrstate::Archive&a,psp_atracState&v){a(v.Buf,v.Size,v.Frames,v.Pos,v.Channels);}
inline void stateFields(rrstate::Archive&a,psp_tagInfo&v){a(v.seed,v.code);}
inline void stateFields(rrstate::Archive&a,psp_Result&v){a(v.Steps,v.PC,v.Reason);}
