// Generated by tools/browser/console-portgen/state.py.
#pragma once
#include "../../../../browser/state/console-translated.h"
inline void stateFields(rrstate::Archive&a,arm_Inst&v){a(v.Addr,v.Len,v.Mnem,v.Text,v.Flow,v.Target,v.HasTarget,v.Thumb,v.TargetThumb,v.Cond);}
inline void stateFields(rrstate::Archive&a,arm_vfpState&v){a(v.S,v.FPSCR,v.FPEXC);}
inline void stateFields(rrstate::Archive&a,arm_CPU&v){a(v.R,v.N,v.Z,v.C,v.V,v.Q,v.GE,v.Thumb,v.BigEndian,v.IRQDisable,v.FIQDisable,v.Mode,v.Arch,v.VFP,v.exclValid,v.exclAddr,v.bankR13,v.bankR14,v.bankSPSR,v.fiqR8_12,v.usrR8_12,v.Halted,v.HaltReason,v.Instrs,v.cur,v.branched);}
inline void stateFields(rrstate::Archive&a,arm_Banks&v){a(v.R13,v.R14,v.SPSR,v.FIQR8_12,v.USRR8_12);}
inline void stateFields(rrstate::Archive&a,sh4_TMUChannel&v){a(v.TCOR,v.TCNT,v.TCR,v.Frac);}
inline void stateFields(rrstate::Archive&a,sh4_TMUState&v){a(v.TOCR,v.TSTR,v.Ch);}
inline void stateFields(rrstate::Archive&a,sh4_CPU&v){a(v.R,v.Rbank,v.SR,v.GBR,v.VBR,v.SSR,v.SPC,v.SGR,v.DBR,v.MACH,v.MACL,v.PR,v.PC,v.fpr,v.FPSCR,v.FPUL,v.MMUCR,v.CCR,v.TRA,v.EXPEVT,v.INTEVT,v.PTEH,v.PTEL,v.TTB,v.TEA,v.QACR0,v.QACR1,v.ICR,v.IPRA,v.IPRB,v.IPRC,v.TMU,v.SQ,v.irlLevel,v.irlCode,v.SerialTX,v.Halted,v.HaltReason,v.Steps,v.nextPC,v.curPC,v.delaySlot,v.pendingDelay,v.onchipRaw,v.onchipGaps);}
inline void stateFields(rrstate::Archive&a,sh4_onchip_137_gap&v){a(v.addr,v.reads);}
inline void stateFields(rrstate::Archive&a,sh4_Inst&v){a(v.Addr,v.Word,v.Len,v.Mnem,v.Text,v.Flow,v.Target,v.HasTarget,v.HasDelay,v.LitAddr,v.LitSize);}
inline void stateFields(rrstate::Archive&a,sh4_State&v){a(v.R,v.Rbank,v.SR,v.GBR,v.VBR,v.SSR,v.SPC,v.SGR,v.DBR,v.MACH,v.MACL,v.PR,v.PC,v.NextPC,v.FPR,v.FPSCR,v.FPUL,v.MMUCR,v.CCR,v.TRA,v.EXPEVT,v.INTEVT,v.PTEH,v.PTEL,v.TTB,v.TEA,v.QACR0,v.QACR1,v.ICR,v.IPRA,v.IPRB,v.IPRC,v.TMU,v.SQ,v.IRLLevel,v.IRLCode,v.SerialTX,v.Halted,v.HaltReason,v.Steps,v.CurPC,v.DelaySlot,v.PendingDelay,v.OnchipRaw,v.OnchipGaps);}
inline void stateFields(rrstate::Archive&a,iso9660_Geometry&v){a(v.SectorSize,v.DataOffset);}
inline void stateFields(rrstate::Archive&a,iso9660_Entry&v){a(v.Name,v.Path,v.IsDir,v.Size,v.Block);}
inline void stateFields(rrstate::Archive&a,dc_aicaTimers&v){a(v.Frac,v.Sub,v.SCIPD,v.MCIPD,v.SampleTick);}
inline void stateFields(rrstate::Archive&a,dc_AICASlot&v){a(v.Active,v.Pos,v.Frac,v.LP,v.EGState,v.EGLevel,v.Cur,v.Prev,v.DecPos,v.AdHist,v.AdStep,v.LoopHist,v.LoopStep,v.LoopSeen);}
inline void stateFields(rrstate::Archive&a,dc_armBus&v){a();}
inline void stateFields(rrstate::Archive&a,dc_gdRequest&v){a(v.Cmd,v.Params,v.Done,v.Result);}
inline void stateFields(rrstate::Archive&a,dc_biosState&v){a(v.NextID,v.Requests);}
inline void stateFields(rrstate::Archive&a,dc_biosHLE&v){a(v.state);}
inline void stateFields(rrstate::Archive&a,dc_Track&v){a(v.Number,v.Mode,v.FileOffset,v.Length,v.StartLBA);}
inline void stateFields(rrstate::Archive&a,dc_Holly&v){a(v.ISTNRM,v.ISTEXT,v.ISTERR,v.IML2NRM,v.IML2EXT,v.IML2ERR,v.IML4NRM,v.IML4EXT,v.IML4ERR,v.IML6NRM,v.IML6EXT,v.IML6ERR);}
inline void stateFields(rrstate::Archive&a,dc_IPBin&v){a(v.HardwareID,v.MakerID,v.DeviceInfo,v.AreaSyms,v.Peripherals,v.ProductNo,v.Version,v.ReleaseDate,v.BootFile,v.Company,v.Title);}
inline void stateFields(rrstate::Archive&a,dc_mapleState&v){a(v.MDSTAR,v.MDTSEL,v.MDEN);}
inline void stateFields(rrstate::Archive&a,dc_PadState&v){a(v.Buttons,v.LT,v.RT,v.JoyX,v.JoyY);}
inline void stateFields(rrstate::Archive&a,dc_WatchRange&v){a(v.Start,v.Len);}
inline void stateFields(rrstate::Archive&a,dc_Machine&v){a(v.RAM,v.VRAM,v.AICARAM,v.Flash,v.CPU,v.ARM,v.ARMRunning,v.AICARegs,v.Timers,v.Slots,v.armAcc,v.Holly,v.C2DStat,v.C2DLen,v.RenderCountdown,v.C2DCountdown,v.C2DPendingBits,v.TAList,v.TAVtx,v.TANeed,v.TAFrame,v.TAClosed,v.TAFifo,v.TAFifoCountdown,v.PVRRegs,v.TAWrites,v.Maple,v.Pad,v.Instrs,v.Fields,v.CurLine,v.FieldNum,v.instrInField,v.bios,v.StopRequested,v.RenderStopAfter,v.WatchW,v.WatchR);}
inline void stateFields(rrstate::Archive&a,dc_pvrVert&v){a(v.x,v.y,v.z,v.u,v.v,v.color,v.offs);}
inline void stateFields(rrstate::Archive&a,dc_renderState&v){a(v.base,v.w,v.h,v.zbuf,v.sprite,v.strip,v.tris,v.px,v.sv,v.texture,v.blend,v.gouraud,v.uv16,v.colType,v.offsEn,v.shade,v.faceCol,v.faceOffs,v.depthCmp,v.zWrite,v.texAddr,v.texMipIx,v.texFmt,v.texTwid,v.texVQ,v.texBank,v.texUW,v.texVH,v.baseCol,v.baseOffs);}
inline void stateFields(rrstate::Archive&a,dc_Result&v){a(v.Steps,v.PC,v.Reason);}
inline void stateFields(rrstate::Archive&a,dc_RunConfig&v){a(v.Breakpoints,v.NoSpin);}
