// Generated by tools/browser/state/generate.py. Explicit format v1 fields.
#pragma once
#include "../../../../browser/state/translated.h"
inline void stateFields(rrstate::Archive&a,n64_ROM&v){a(v.Data,v.MD5);}
inline void stateFields(rrstate::Archive&a,r4300_TLBEntry&v){a(v.PageMask,v.EntryHi,v.EntryLo0,v.EntryLo1);}
inline void stateFields(rrstate::Archive&a,r4300_CPU&v){a(v.R,v.HI,v.LO,v.PC,v.nextPC,v.COP0,v.TLB,v.FGR,v.FCR31,v.COP2Latch,v.LLBit,v.Halted,v.HaltReason,v.Steps,v.curPC,v.delaySlot,v.pendingDelay,v.branchAddr,v.countFrac);}
inline void stateFields(rrstate::Archive&a,rsp_CPU&v){a(v.R,v.V,v.Acc,v.VCO,v.VCC,v.VCE,v.divIn,v.divOut,v.divInLoaded,v.PC,v.nextPC,v.Halted,v.Broke,v.HaltReason,v.Steps,v.Unimplemented,v.curPC);}
inline void stateFields(rrstate::Archive&a,n64_ai&v){a(v.Regs);}
inline void stateFields(rrstate::Archive&a,n64_BootConfig&v){a(v.TVType,v.ResetType,v.OSVersion);}
inline void stateFields(rrstate::Archive&a,n64_isv&v){a(v.Buf,v.Lines);}
inline void stateFields(rrstate::Archive&a,n64_mi&v){a(v.InitMode,v.Intr,v.Mask);}
inline void stateFields(rrstate::Archive&a,n64_pi&v){a(v.DramAddr,v.CartAddr,v.Status,v.Regs);}
inline void stateFields(rrstate::Archive&a,n64_vi&v){a(v.Regs,v.Acc,v.Current);}
inline void stateFields(rrstate::Archive&a,n64_si&v){a(v.Regs,v.DramAddr);}
inline void stateFields(rrstate::Archive&a,n64_rdpImage&v){a(v.Format,v.Size,v.Width,v.Addr);}
inline void stateFields(rrstate::Archive&a,Anon12&v){a(v.XH,v.YH,v.XL,v.YL);}
inline void stateFields(rrstate::Archive&a,n64_tile&v){a(v.Format,v.Size,v.Line,v.TMem,v.Palette,v.CMS,v.CMT,v.MaskS,v.MaskT,v.ShiftS,v.ShiftT,v.SL,v.TL,v.SH,v.TH);}
inline void stateFields(rrstate::Archive&a,n64_rdp&v){a(v.Color,v.Texture,v.Mask,v.Scissor,v.OtherModes,v.Combine,v.FillColor,v.FogColor,v.BlendColor,v.PrimColor,v.EnvColor,v.PrimDepth,v.Tiles,v.TMem,v.Pending);}
inline void stateFields(rrstate::Archive&a,n64_Controller&v){a(v.Present,v.Buttons,v.StickX,v.StickY);}
inline void stateFields(rrstate::Archive&a,n64_runState&v){a(v.breakpoints);}
inline void stateFields(rrstate::Archive&a,n64_Machine&v){a(v.RDRAM,v.DMEM,v.IMEM,v.PIF,v.romMD5,v.CPU,v.RSP,v.mi,v.pi,v.vi,v.ai,v.si,v.isv,v.rdp,v.ri,v.rd,v.sp,v.spPC,v.dp,v.Controllers,v.EEPROM,v.run,v.noSpin,v.rspRunning,v.rspSteps,v.rdpWords,v.Log,v.logSeen,v.WatchLo,v.WatchHi,v.RWatchLo,v.RWatchHi,v.ContPolls,v.JoybusCmds,v.SIWrites,v.SIReads,v.StopRequested,v.rdpStopAt,v.rdpCount,v.hookMuted);}
inline void stateFields(rrstate::Archive&a,n64_rdpStop&v){a();}
inline void stateFields(rrstate::Archive&a,n64_rgba&v){a(v.R,v.G,v.B,v.A);}
inline void stateFields(rrstate::Archive&a,n64_combineInputs&v){a(v.Texel0,v.Texel1,v.Shade,v.Prim,v.Env,v.Key,v.Comb,v.LODFrac,v.PrimLODFrac,v.texS,v.texT);}
inline void stateFields(rrstate::Archive&a,n64_uint32Vec3&v){a(v.R,v.G,v.B);}
inline void stateFields(rrstate::Archive&a,n64_combinerSelects&v){a(v.subAC,v.subBC,v.mulC,v.addC,v.subAA,v.subBA,v.mulA,v.addA);}
inline void stateFields(rrstate::Archive&a,n64_PixelEvent&v){a(v.Drawn,v.ZReject,v.AlphaReject,v.R,v.G,v.B,v.A,v.Z,v.TexR,v.TexG,v.TexB,v.TexA,v.TexS,v.TexT);}
inline void stateFields(rrstate::Archive&a,n64_triAttrs&v){a(v.base,v.dx,v.de);}
inline void stateFields(rrstate::Archive&a,n64_Result&v){a(v.Steps,v.PC,v.Reason);}
inline void stateFields(rrstate::Archive&a,Anon18&v){a(v.base,v.shift);}
