// Generate the browser's official 6510 instruction table from the native decoder.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"retroreverse.com/tools/cpu/mos6502"
)

func main() {
	out := flag.String("out", "site/emulators/opcodes6502.js", "output")
	check := flag.Bool("check", false, "check generated file")
	flag.Parse()
	b, e := json.Marshal(mos6502.Opcodes())
	if e != nil {
		panic(e)
	}
	b = append([]byte("// Generated by tools/cmd/dis6502export; edit tools/cpu/mos6502.\nexport const opcodes = "), b...)
	b = append(b, []byte(";\n")...)
	if *check {
		old, e := os.ReadFile(*out)
		if e != nil || !bytes.Equal(old, b) {
			panic("stale opcode table")
		}
		return
	}
	if e := os.WriteFile(*out, b, 0644); e != nil {
		panic(e)
	}
	fmt.Println(*out)
}
