#!/usr/bin/env python3
"""Explicit serialized fields for the console ports. Host links are rebound on load."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[3]
skip={
'gekko_CPU':{'bus','fetcher'},'gcdsp_CPU':{'bus'},
'gc_Machine':{'RAM','ARAM','disc','discMD5','Log','logSeen','prof','stack'},
'gc_gpu':{'workers','tris'},
'gc_tevStage':{'rrOperands'},'gc_tevState':{'rrPrepared'},
'vu_VU':{'Micro','Data'},'r5900_CPU':{'bus'},'mips_CPU':{'bus','GTE'},
'ps2_Machine':{'ram','vol','exe','extraSyms','rasterPool','prof','Log','logSeen','weaveRing'},
'ps2_IOP':{'ram','ps2','logPC'},'ps2_GS':{'m','rrFeatures'},'ps2_vif':{'m'},
}
for platform in ['gc','ps2']:
 source=(root/f'tools/platform/{platform}/browser/core/generated.cpp').read_text()
 out=['// Generated by tools/browser/console-portgen/state.py.','#pragma once','#include "../../../../browser/state/console-translated.h"']
 for start in re.finditer(r'struct (\w+)\s*\{',source):
  name=start[1]
  if name.startswith('Anon') or name in {'gc_Disc','iso9660_Volume','iso9660_Source'}:continue
  depth=1;i=start.end()
  while depth:
   depth+=(source[i]=='{')-(source[i]=='}');i+=1
  body=source[start.end():i-1]
  body=re.sub(r'(?:bool|auto) operator[^;]+;','',body)
  fields=[]
  for field in body.split(';'):
   field=field.strip()
   if not field or 'std::function' in field:continue
   # Host clock fields are declared together in the generator.
   if field=='uint64_t rrVblAcc{},rrIopAcc{}':fields+=['v.rrVblAcc','v.rrIopAcc'];continue
   m=re.search(r'(\w+)\s*(?:\{\})?$',field)
   if not m:raise Exception((name,field))
   if m[1] not in skip.get(name,set()):fields.append('v.'+m[1])
  out.append(f'inline void stateFields(rrstate::Archive&a,{name}&v){{a('+','.join(fields)+');}')
 (root/f'tools/platform/{platform}/browser/core/state-fields.h').write_text('\n'.join(out)+'\n')
