// Generated by tools/browser/console-portgen/state.py.
#pragma once
#include "../../../../browser/state/console-translated.h"
inline void stateFields(rrstate::Archive&a,arm_Inst&v){a(v.Addr,v.Len,v.Mnem,v.Text,v.Flow,v.Target,v.HasTarget,v.Thumb,v.TargetThumb,v.Cond);}
inline void stateFields(rrstate::Archive&a,arm_vfpState&v){a(v.S,v.FPSCR,v.FPEXC);}
inline void stateFields(rrstate::Archive&a,arm_CPU&v){a(v.R,v.N,v.Z,v.C,v.V,v.Q,v.GE,v.Thumb,v.BigEndian,v.IRQDisable,v.FIQDisable,v.Mode,v.Arch,v.VFP,v.exclValid,v.exclAddr,v.bankR13,v.bankR14,v.bankSPSR,v.fiqR8_12,v.usrR8_12,v.Halted,v.HaltReason,v.Instrs,v.cur,v.branched);}
inline void stateFields(rrstate::Archive&a,arm_Banks&v){a(v.R13,v.R14,v.SPSR,v.FIQR8_12,v.USRR8_12);}
inline void stateFields(rrstate::Archive&a,gba_Header&v){a(v.EntryInstr,v.EntryAddr,v.LogoMD5,v.Title,v.GameCode,v.MakerCode,v.Fixed96,v.UnitCode,v.DeviceType,v.Version,v.Checksum,v.ChecksumOK);}
inline void stateFields(rrstate::Archive&a,gba_ROM&v){a(v.Data,v.Header);}
inline void stateFields(rrstate::Archive&a,gbamachine_bus&v){a();}
inline void stateFields(rrstate::Archive&a,gbamachine_dmaChan&v){a(v.src,v.dst,v.latchSrc,v.latchDst,v.count,v.ctrl);}
inline void stateFields(rrstate::Archive&a,gbamachine_eeprom&v){a(v.present,v.data,v.sized,v.inBits,v.outBits,v.ready);}
inline void stateFields(rrstate::Archive&a,gbamachine_video&v){a(v.line,v.hblank,v.frames);}
inline void stateFields(rrstate::Archive&a,gbamachine_ppu&v){a(v.bg2x,v.bg2y,v.bg3x,v.bg3y);}
inline void stateFields(rrstate::Archive&a,gbamachine_timer&v){a(v.counter,v.reload,v.ctrl,v.frac);}
inline void stateFields(rrstate::Archive&a,gbamachine_Machine&v){a(v.cpu,v.ewram,v.iwram,v.pal,v.vram,v.oam,v.io,v.ime,v.ie,v.if_,v.waiting,v.waitAny,v.waitMask,v.vid,v.ppu,v.apu,v.dma,v.timers,v.eeprom,v.keys,v.Steps,v.screen,v.stop,v.stopped,v.stoppedPC);}
inline void stateFields(rrstate::Archive&a,gbamachine_lineBuf&v){a(v.c,v.on);}
inline void stateFields(rrstate::Archive&a,gbamachine_Result&v){a(v.Steps,v.Frames,v.Reason,v.Milestone);}
inline void stateFields(rrstate::Archive&a,gbamachine_square&v){a(v.enabled,v.hasSweep,v.phase,v.dutySel,v.freq,v.length,v.lengthEn,v.vol,v.envDir,v.envPeriod,v.envTimer,v.swPeriod,v.swShift,v.swDir,v.swTimer,v.swOn,v.swShadow);}
inline void stateFields(rrstate::Archive&a,gbamachine_waveCh&v){a(v.enabled,v.dacOn,v.phase,v.freq,v.length,v.lengthEn,v.volShift,v.force75,v.ram,v.bank,v.twoBanks);}
inline void stateFields(rrstate::Archive&a,gbamachine_noiseCh&v){a(v.enabled,v.lfsr,v.timer,v.length,v.lengthEn,v.vol,v.envDir,v.envPeriod,v.envTimer,v.divisor,v.shift,v.width7);}
inline void stateFields(rrstate::Archive&a,gbamachine_fifo&v){a(v.q,v.cur);}
inline void stateFields(rrstate::Archive&a,gbamachine_apu&v){a(v.ch1,v.ch2,v.ch3,v.ch4,v.dsA,v.dsB,v.powered,v.frameAcc,v.frameSeq,v.mixRegL,v.mixRegH,v.sampleAcc);}
