// Generated by ../slice.py. Scheduler locals survive browser yields.
#pragma once
inline uint64_t rrSchedulerClockBase=0;
inline std::function<bool(threedo_Machine*,uint32_t)> rrSchedulerBoundary;
struct RunContext {
 bool prepared=false;
 uint64_t steps=0,sinceNew=0;
 Map<uint32_t,bool> seen;
 std::array<uint32_t,64> ring{};
 int64_t ri=0,unstickTries=0,stallSwitches=0;
};
inline threedo_Result threedo_Machine_RunSlice(threedo_Machine* m,uint64_t budget, RunContext& context){
{
threedo_Machine_profRunEnter(m);
auto tmp177=defer([&](){threedo_Machine_profRunExit(m);});
auto& steps=context.steps; const auto initial=steps; const auto maxSteps=initial+budget;
auto& seen=context.seen;
auto& sinceNew=context.sinceNew;
constexpr int64_t noProgress=1000000ULL;
constexpr int64_t switchAt=20000ULL;
auto& ring=context.ring;
auto& ri=context.ri;
auto& unstickTries=context.unstickTries;
auto& stallSwitches=context.stallSwitches;
for (;(steps < maxSteps);){
if(m->MovieHLE && m->moviePos<m->movieQueue.n)return threedo_Result{steps-initial,m->CPU->R[15],"movie pending"};
if (m->StopRequested) {
m->StopRequested = false;
return threedo_Result{steps-initial,arm60_CPU_Reg(m->CPU,cast<uint32_t>(15ULL)),std::string("stop requested",14)};
}
if(!context.prepared){
if (((!m->PaceFields) && (modi<uint64_t>(steps,threedo_vblankPeriod) == cast<uint64_t>(0ULL)))) {
threedo_Machine_advanceVBlank(m,cast<uint32_t>(1ULL));
}
for (;((len(m->PadScript) > cast<int64_t>(0ULL)) && (steps >= m->PadScript[cast<int64_t>(0ULL)].AtStep));){
threedo_Machine_SendPadEvent(m,m->PadScript[cast<int64_t>(0ULL)].Buttons);
m->PadScript = sub(m->PadScript,cast<int64_t>(1ULL),len(m->PadScript));
}
context.prepared=true;
}
uint32_t pc = arm60_CPU_Reg(m->CPU,cast<uint32_t>(15ULL));
if(rrSchedulerBoundary && rrSchedulerBoundary(m,pc))return threedo_Result{steps-initial,pc,"debug boundary"};
context.prepared=false;
if ((pc == threedo_taskExitTramp)) {
threedo_Machine_curTask(m)->state = threedo_stDone;
if ((!threedo_Machine_switchTask(m))) {
if ((!threedo_Machine_wakeByFieldTick(m))) {
return threedo_Result{steps-initial,pc,go_fmt_Sprintf(std::string("all tasks finished (%d switches)",32),m->switches)};
}
}
continue;
}
if (((pc >= threedo_hleBase) && (pc < cast<uint32_t>((threedo_hleBase + threedo_hleSize))))) {
threedo_Machine_serviceKernelCall(m,pc);
steps++;
if (m->needSchedule) {
m->needSchedule = false;
if ((!threedo_Machine_switchTask(m))) {
if (threedo_Machine_wakeByFieldTick(m)) {
auto tmp178 = std::make_tuple(cast<uint64_t>(0ULL),cast<int64_t>(0ULL));
sinceNew = std::get<0>(tmp178);
stallSwitches = std::get<1>(tmp178);
}
else {
threedo_Machine_curTask(m)->state = threedo_stRunning;
}
}
}
continue;
}
if (m->Halted) {
return threedo_Result{steps-initial,pc,m->HaltReason};
}
if (bool(m->OnStep)) {
m->OnStep(m,pc);
if (m->StopRequested) {
m->StopRequested = false;
return threedo_Result{steps-initial,pc,std::string("stop requested",14)};
}
}
ring[cast<int64_t>((ri & cast<int64_t>(63ULL)))] = pc;
ri++;
if ((pc < threedo_dramSize)) {
if ((!get(seen,pc))) {
seen[pc] = true;
sinceNew = cast<uint64_t>(0ULL);
stallSwitches = cast<int64_t>(0ULL);
}
else {
sinceNew++;
if ((modi<uint64_t>(sinceNew,switchAt) == cast<uint64_t>(0ULL))) {
bool woke = false;
if (m->PaceFields) {
woke = threedo_Machine_fieldTick(m);
}
threedo_Machine_curTask(m)->state = threedo_stReady;
bool switched = threedo_Machine_switchTask(m);
if (woke) {
stallSwitches = cast<int64_t>(0ULL);
sinceNew = cast<uint64_t>(0ULL);
continue;
}
if (switched) {
stallSwitches++;
if ((stallSwitches > cast<int64_t>(((cast<int64_t>((cast<int64_t>((cast<int64_t>(32ULL) * len(m->tasks))) + cast<int64_t>(8ULL)))) * gmax(cast<int64_t>(1ULL),m->StallTolerance))))) {
return threedo_Result{steps-initial,pc,go_fmt_Sprintf(std::string("deadlock: all %d tasks stalled near 0x%08X",42),len(m->tasks),pc)};
}
sinceNew = cast<uint64_t>(0ULL);
continue;
}
threedo_Machine_curTask(m)->state = threedo_stRunning;
if ((m->SpinBreak && threedo_Machine_isFlagSpin(m,sub(ring,0,len(ring))))) {
{
Slice<uint32_t> poked = threedo_Machine_breakSpin(m,sub(ring,0,len(ring)));
if (((len(poked) > cast<int64_t>(0ULL)) && (unstickTries < cast<int64_t>(2000ULL)))) {
unstickTries++;
m->SpinBreaks++;
sinceNew = cast<uint64_t>(0ULL);
}
}
}
}
if ((sinceNew > noProgress)) {
return threedo_Result{steps-initial,pc,go_fmt_Sprintf(std::string("no forward progress (0x%08X, %d switches, %d tasks)",51),pc,m->switches,len(m->tasks))};
}
}
}
arm60_CPU_Step(m->CPU);
steps++;
if (m->needSchedule) {
m->needSchedule = false;
if ((!threedo_Machine_switchTask(m))) {
if (threedo_Machine_wakeByFieldTick(m)) {
auto tmp179 = std::make_tuple(cast<uint64_t>(0ULL),cast<int64_t>(0ULL));
sinceNew = std::get<0>(tmp179);
stallSwitches = std::get<1>(tmp179);
}
else {
threedo_Machine_curTask(m)->state = threedo_stRunning;
}
}
}
if (m->CPU->Halted) {
return threedo_Result{steps-initial,arm60_CPU_CurPC(m->CPU),(std::string("cpu: ",5) + m->CPU->HaltReason)};
}
if (m->Halted) {
return threedo_Result{steps-initial,arm60_CPU_CurPC(m->CPU),m->HaltReason};
}
}
return threedo_Result{steps-initial,arm60_CPU_Reg(m->CPU,cast<uint32_t>(15ULL)),std::string("step budget reached",19)};
}
}
