// Generated by tools/browser/state/generate.py. Explicit format v1 fields.
#pragma once
#include "../../../../browser/state/translated.h"
inline void stateFields(rrstate::Archive&a,sm83_CPU&v){a(v.A,v.F,v.B,v.C,v.D,v.E,v.H,v.L,v.SP,v.PC,v.IME,v.imeEnable,v.Halted,v.HaltReason,v.halt,v.Stopped,v.Instrs,v.takenExtra);}
inline void stateFields(rrstate::Archive&a,gameboy_Machine&v){a(v.CPU,v.nbanks,v.romBank,v.ramBank,v.ramEnable,v.mode,v.vram,v.wram,v.oam,v.hram,v.io,v.extram,v.ie,v.divCounter,v.timaCounter,v.lcdDot,v.Cycles,v.Buttons,v.Sample,v.WatchLo,v.WatchHi);}
inline void stateFields(rrstate::Archive&a,Anon0&v){a(v.A,v.F,v.B,v.C,v.D,v.E,v.H,v.L,v.SP,v.PC,v.IME,v.imeEnable,v.Halted,v.HaltReason,v.halt,v.Stopped,v.Instrs,v.bus,v.takenExtra);}
inline void stateFields(rrstate::Archive&a,Anon1&v){a(v.CPU,v.rom,v.nbanks,v.romBank,v.ramBank,v.ramEnable,v.mode,v.vram,v.wram,v.oam,v.hram,v.io,v.extram,v.ie,v.divCounter,v.timaCounter,v.lcdDot,v.Cycles,v.Buttons,v.Sample,v.PCHist,v.WatchLo,v.WatchHi,v.WatchPCs);}
