#pragma once
#include "../../../../browser/core/capture.h"
#include "../../../../browser/core/profile.h"
namespace rr3ds {
struct Region{uint32_t guest,offset,size;};
inline std::vector<Region>regions;
inline std::array<n3ds_xferRecord,2>screens;
inline uint32_t address(uint32_t a){for(auto r:regions)if(a>=r.guest&&uint64_t(a-r.guest)<r.size)return r.offset+(a-r.guest);return UINT32_MAX;}
inline std::vector<uint8_t>memory(n3ds_Machine*m,bool initial=false){std::vector<uint8_t>b;if(initial){regions.clear();for(auto r:m->regions){auto inside=[r](uint32_t a){return a>=r->base&&uint64_t(a-r->base)<uint64_t(r->data.n);};bool target=r->name=="vram"||r->name=="linear";for(auto fb:m->screenFB)target|=inside(fb.AddrLeft);auto[color,w,h]=n3ds_GPU_ColorTarget(m->gpu);auto[depth,dw,dh]=n3ds_GPU_DepthTarget(m->gpu);target|=inside(color)||inside(depth);if(!target)continue;if(uint64_t(b.size())+r->data.n>128*1024*1024)throw std::runtime_error("Capture memory limit");regions.push_back({r->base,uint32_t(b.size()),uint32_t(r->data.n)});b.insert(b.end(),r->data.begin(),r->data.end());}}else{for(auto r:regions)for(uint32_t i=0;i<r.size;i++)b.push_back(n3ds_Machine_Read(m,r.guest+i));}return b;}
inline void clean(){auto&t=rrcapture::trace;t.source=t.palette=t.texel=t.sourceValue=t.paletteValue=t.sourceBefore=t.paletteBefore=0;t.u=t.v=0;}
struct Command{uint32_t previous;Command(n3ds_Machine*m,const char*kind,uint32_t a=0,uint32_t b=0,uint32_t c=0,uint32_t d=0):previous(rrcapture::trace.current){if(rrcapture::trace.active){clean();std::ostringstream s;s<<"{\"kind\":\""<<kind<<"\",\"a\":"<<a<<",\"b\":"<<b<<",\"c\":"<<c<<",\"d\":"<<d<<",\"addressSpace\":\"capture-local packed RAM; command addresses are guest virtual/physical\",\"hasSource\":"<<((std::string(kind)=="GX display transfer")?"true":"false")<<",\"sourceSize\":4}";rrcapture::trace.event(m->instrs,m->CPU->R[15],s.str());}}~Command(){rrcapture::trace.current=previous;clean();}};
inline void source(uint32_t guest){auto&t=rrcapture::trace;if(!t.active)return;t.source=address(guest);t.sourceBefore=t.writes.size();t.sourceValue=t.value(t.shadow,t.source,4);}
inline void write(n3ds_Machine*m,uint32_t guest,uint32_t v,uint32_t pc){auto&t=rrcapture::trace;auto a=address(guest);if(a==UINT32_MAX)return;v&=255;
 if(!t.writes.empty()){auto&w=t.writes.back();if(w.flags==1&&w.size<4&&w.event==t.current&&w.clock==m->instrs&&w.pc==pc&&w.source==t.source&&w.sourceBefore==t.sourceBefore){if(a==w.address+w.size){w.before|=t.value(t.shadow,a,1)<<(8*w.size);w.after|=v<<(8*w.size);w.size++;t.shadow[a]=v;return;}if(a+1==w.address){w.before=(w.before<<8)|t.value(t.shadow,a,1);w.after=(w.after<<8)|v;w.address=a;w.size++;t.shadow[a]=v;return;}}}
 t.record(a,v,1,m->instrs,pc,t.current);
}
inline void screenGeometry(n3ds_Machine*m){for(int i=0;i<2;i++){auto r=i?m->lastXferBottom:m->lastXferTop;auto fb=m->screenFB[i];if(fb.Valid&&fb.AddrLeft){r.dst=fb.AddrLeft;auto bpp=n3ds_fbBPP(fb.Format);if(bpp){r.bpp=bpp;r.format=fb.Format&7;if(fb.Stride)r.stride=fb.Stride/bpp;}if(!r.w||!r.h){r.w=240;r.h=i?320:400;}}screens[i]=r;}}
inline uint32_t pixelAddress(int x,int y){if(x<0||x>=400||y<0||y>=480)return UINT32_MAX;int screen=y/240;y%=240;if(screen)x-=40;auto r=screens[screen];if(x<0||x>=int(r.h)||y>=int(r.w)||!r.dst||!r.bpp)return UINT32_MAX;return address(r.dst+(uint32_t(x)*r.stride+r.w-1-y)*r.bpp);}
inline std::vector<uint8_t>display(const std::vector<uint8_t>&b){std::vector<uint8_t>out(400*480*4);for(int y=0;y<480;y++)for(int x=0;x<400;x++){uint32_t c[4]={0,0,0,255};auto a=pixelAddress(x,y);auto r=screens[y/240];if(a!=UINT32_MAX&&uint64_t(a)+r.bpp<=b.size()){uint32_t v=0;for(uint32_t k=0;k<r.bpp;k++)v|=uint32_t(b[a+k])<<(8*k);switch(r.format){case 0:c[0]=v>>24;c[1]=(v>>16)&255;c[2]=(v>>8)&255;break;case 1:c[0]=(v>>16)&255;c[1]=(v>>8)&255;c[2]=v&255;break;case 2:c[0]=(((v>>11)&31)<<3|((v>>11)&31)>>2);c[1]=(((v>>5)&63)<<2|((v>>5)&63)>>4);c[2]=((v&31)<<3|(v&31)>>2);break;case 3:c[0]=(((v>>11)&31)<<3|((v>>11)&31)>>2);c[1]=(((v>>6)&31)<<3|((v>>6)&31)>>2);c[2]=(((v>>1)&31)<<3|((v>>1)&31)>>2);break;case 4:c[0]=((v>>12)&15)*17;c[1]=((v>>8)&15)*17;c[2]=((v>>4)&15)*17;break;}}for(int k=0;k<4;k++)out[(y*400+x)*4+k]=c[k];}return out;}
}
