// Generated by tools/browser/state/generate.py. Explicit format v1 fields.
#pragma once
#include "../../../../browser/state/translated.h"
inline void stateFields(rrstate::Archive&a,z80_CPU&v){a(v.A,v.F,v.B,v.C,v.D,v.E,v.H,v.L,v.A2,v.F2,v.B2,v.C2,v.D2,v.E2,v.H2,v.L2,v.IX,v.IY,v.SP,v.PC,v.I,v.R,v.IFF1,v.IFF2,v.IM,v.Halted,v.HaltReason,v.waiting,v.Instrs,v.intReq,v.eiPending,v.idx,v.usesHL,v.disp,v.dispSet);}
inline void stateFields(rrstate::Archive&a,gamegear_VDP&v){a(v.VRAM,v.CRAM,v.Regs,v.addr,v.code,v.latch,v.latched,v.readBuf,v.status,v.line,v.Writes,v.CRAMWrites);}
inline void stateFields(rrstate::Archive&a,gamegear_CapEntry&v){a(v.HL,v.BC,v.DE,v.Slot1);}
inline void stateFields(rrstate::Archive&a,gamegear_PSG&v){a(v.Reg,v.latch);}
inline void stateFields(rrstate::Archive&a,gamegear_Machine&v){a(v.CPU,v.VDP,v.PSG,v.nbanks,v.ram,v.slot,v.Pad00,v.PadDC,v.Sample,v.RAMWatchLo,v.RAMWatchHi,v.stepPC,v.CapturePC,v.CapHL,v.CapBC,v.CapSlot1,v.Captured,v.CapLo,v.CapHi,v.CapOutBase,v.CapOut,v.CapOutDone,v.WatchLo,v.WatchHi);}
inline void stateFields(rrstate::Archive&a,Anon0&v){a(v.A,v.F,v.B,v.C,v.D,v.E,v.H,v.L,v.A2,v.F2,v.B2,v.C2,v.D2,v.E2,v.H2,v.L2,v.IX,v.IY,v.SP,v.PC,v.I,v.R,v.IFF1,v.IFF2,v.IM,v.Halted,v.HaltReason,v.waiting,v.Instrs,v.bus,v.intReq,v.eiPending,v.idx,v.usesHL,v.disp,v.dispSet);}
inline void stateFields(rrstate::Archive&a,Anon1&v){a(v.VRAM,v.CRAM,v.Regs,v.addr,v.code,v.latch,v.latched,v.readBuf,v.status,v.line,v.Writes,v.CRAMWrites,v.CRAMLineLog);}
inline void stateFields(rrstate::Archive&a,Anon2&v){a(v.HL,v.BC,v.DE,v.Slot1);}
inline void stateFields(rrstate::Archive&a,Anon3&v){a(v.CPU,v.VDP,v.PSG,v.rom,v.nbanks,v.ram,v.slot,v.Pad00,v.PadDC,v.Sample,v.PCHist,v.RAMWatchLo,v.RAMWatchHi,v.RAMWatchPCs,v.stepPC,v.CapturePC,v.CapHL,v.CapBC,v.CapSlot1,v.Captured,v.CapLog,v.CapLo,v.CapHi,v.CapOutBase,v.CapOut,v.CapOutDone,v.WatchLo,v.WatchHi,v.WatchPCs);}
inline void stateFields(rrstate::Archive&a,Anon4&v){a(v.Reg,v.latch);}
