// Generated by tools/browser/console-portgen/state.py.
#pragma once
#include "../../../../browser/state/console-translated.h"
inline void stateFields(rrstate::Archive&a,x86_FPUState&v){a(v.St,v.Tag,v.Top,v.Ctrl,v.Stat);}
inline void stateFields(rrstate::Archive&a,x86_CPU&v){a(v.Regs,v.Seg,v.IP,v.instrIP,v.CF,v.PF,v.AF,v.ZF,v.SF,v.TF,v.IF,v.DF,v.OF,v.Halted,v.HaltReason,v.Steps,v.Ext386,v.Mode,v.SegBase,v.ssShadow,v.FPU,v.XMM,v.MMX,v.MXCSR,v.TSCMul,v.dSeg,v.dOpsize,v.dAddrsize);}
inline void stateFields(rrstate::Archive&a,x86_ea&v){a(v.isReg,v.reg,v.base,v.off);}
inline void stateFields(rrstate::Archive&a,dos_COFFSection&v){a(v.Name,v.VAddr,v.Size,v.FileOff,v.Flags,v.Data);}
inline void stateFields(rrstate::Archive&a,dos_COFF&v){a(v.StubEnd,v.NSections,v.Flags,v.Entry,v.TextStart,v.DataStart,v.TextSize,v.DataSize,v.BSSSize,v.Sections);}
inline void stateFields(rrstate::Archive&a,dos_dos_432_kv&v){a(v.ah,v.n);}
inline void stateFields(rrstate::Archive&a,dos_findState&v){a(v.matches,v.idx);}
inline void stateFields(rrstate::Archive&a,dos_injEvent&v){a(v.kind,v.code,v.x,v.y,v.delay);}
inline void stateFields(rrstate::Archive&a,dos_Machine&v){a(v.CPU,v.gameDir,v.files,v.pspSeg,v.envSeg,v.loadSeg,v.memTop,v.firstMCB,v.dtaSeg,v.dtaOff,v.finds,v.scratchDir,v.IntCounts,v.otherInts,v.OverlayCalls,v.ems,v.io,v.video,v.vga,v.ms,v.keyEvents,v.keyWait,v.keyHits,v.keyRetry,v.EnableIRQ,v.WatchAddr,v.WatchLen,v.watchHits,v.VGAProfileAt,v.ProfLo,v.ProfHi,v.RdProfileAt,v.RdLo,v.RdHi,v.Terminated,v.ExitCode,v.Int33Hist);}
inline void stateFields(rrstate::Archive&a,dos_VGAWriter&v){a(v.Seg,v.Off,v.Count);}
inline void stateFields(rrstate::Archive&a,dos_emsHandle&v){a(v.base,v.count);}
inline void stateFields(rrstate::Archive&a,dos_emsState&v){a(v.backing,v.nextPage,v.handles,v.nextH,v.slot,v.saved);}
inline void stateFields(rrstate::Archive&a,dos_ioState&v){a(v.kbdOut,v.kbdOutFull,v.expectData,v.retrace,v.pit,v.oplReg,v.oplTimer,v.tick,v.mixReg,v.mixRegs,v.dspQueue,v.dspReset,v.dacIndex,v.Pal,v.seen);}
inline void stateFields(rrstate::Archive&a,dos_mouseState&v){a(v.x,v.y,v.accX,v.accY,v.buttons,v.xMin,v.xMax,v.yMin,v.yMax,v.hidden,v.pressL,v.pressR);}
inline void stateFields(rrstate::Archive&a,dos_vgaState&v){a(v.planes,v.latch,v.seqIdx,v.seq,v.gcIdx,v.gc,v.crtcIdx,v.crtc);}
inline void stateFields(rrstate::Archive&a,dos_pitState&v){a(v.reload,v.writeHi,v.latched,v.haveLatch,v.readHi);}
inline void stateFields(rrstate::Archive&a,dos_pmVector&v){a(v.sel,v.off,v.set);}
inline void stateFields(rrstate::Archive&a,dos_PM&v){a(v.CPU,v.gameDir,v.files,v.convBase,v.convNext,v.convTop,v.heapBase,v.heapNext,v.stackFloor,v.infoBase,v.imgEnd,v.wWLo,v.wWHi,v.wRLo,v.wRHi,v.nextSel,v.nextCallback,v.sels,v.virtIF,v.lolSeg,v.lolOff,v.dtaSeg,v.dtaOff,v.pit,v.retrace,v.pmVectors,v.defIntVec,v.keyEvents,v.injKeys,v.keyWait,v.keyRetry,v.injTick,v.keyHits,v.kbdData,v.kbdFull,v.dacIndex,v.Pal,v.DPMICounts,v.IntCounts,v.DOSCounts,v.Terminated,v.ExitCode,v.Console,v.rrQuakeBase);}
inline void stateFields(rrstate::Archive&a,dos_MemRegion&v){a(v.Name,v.Lo,v.Hi);}
inline void stateFields(rrstate::Archive&a,dos_rmcs&v){a(v.addr,v.edi,v.esi,v.ebp,v.ebx,v.edx,v.ecx,v.eax,v.flags,v.es,v.ds,v.fs,v.gs,v.ip,v.cs,v.sp,v.ss);}
inline void stateFields(rrstate::Archive&a,dos_Reloc&v){a(v.Segment,v.Offset);}
inline void stateFields(rrstate::Archive&a,dos_MZ&v){a(v.LastPageBytes,v.Pages,v.Relocations,v.HeaderParas,v.MinAlloc,v.MaxAlloc,v.InitSS,v.InitSP,v.Checksum,v.InitIP,v.InitCS,v.RelocOffset,v.OverlayNumber,v.FileSize,v.LoadImageEnd,v.LoadModuleOffset,v.LoadModuleSize,v.AppendedSize,v.Relocs);}
