package knowledge

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
)

type Label struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Region      string `json:"region"`
	Start       uint64 `json:"start"`
	Length      uint64 `json:"length"`
	Description string `json:"description"`
	Source      string `json:"source"`
}
type BrowserRelease struct {
	Executable string   `json:"executable,omitempty"`
	ID         string   `json:"id"`
	Media      []Media  `json:"media,omitempty"`
	FileSet    *FileSet `json:"fileSet,omitempty"`
	Labels     []Label  `json:"labels"`
}
type BrowserPackage struct {
	ID           string           `json:"id"`
	Platform     string           `json:"platform"`
	Revision     uint64           `json:"revision"`
	SourceSHA256 string           `json:"sourceSHA256"`
	Releases     []BrowserRelease `json:"releases"`
	Knowledge    json.RawMessage  `json:"knowledge"`
}

func contains(a []string, s string) bool {
	for _, v := range a {
		if v == s {
			return true
		}
	}
	return false
}
func (p *Package) BrowserData() (BrowserPackage, error) {
	out := BrowserPackage{ID: p.ID, Platform: p.Game.System.ID, Revision: p.Revision, SourceSHA256: p.Hash, Knowledge: p.Raw}
	for _, id := range keys(p.Releases) {
		r := p.Releases[id]
		b := BrowserRelease{ID: id, Executable: r.Executable, Media: r.Media, FileSet: r.FileSet, Labels: []Label{}}
		for _, key := range keys(p.Regions) {
			d := p.Regions[key]
			if !d.MemoryLabel || !contains(d.Releases, id) {
				continue
			}
			s, e := p.Resolve(d.Location, id)
			if e != nil {
				return out, e
			}
			description := d.Description + " Applicability: " + d.Applicability
			evidence := p.Evidence[d.Evidence[0]]
			description += " Evidence: " + evidence.Status + "."
			if evidence.Limitations != "" {
				description += " " + evidence.Limitations
			}
			b.Labels = append(b.Labels, Label{ID: key, Name: d.Label, Region: s.Region, Start: s.Offset, Length: d.Length, Description: description, Source: p.Sources[evidence.Source].Path})
		}
		out.Releases = append(out.Releases, b)
	}
	return out, nil
}

// ExportJS compiles data only. No user-supplied strings become executable code.
func ExportJS(packages []*Package) ([]byte, error) {
	packages = append([]*Package(nil), packages...)
	sort.Slice(packages, func(i, j int) bool { return packages[i].ID < packages[j].ID })
	seen := map[string]bool{}
	data := []BrowserPackage{}
	for _, p := range packages {
		if seen[p.ID] {
			return nil, fmt.Errorf("duplicate package %s", p.ID)
		}
		seen[p.ID] = true
		d, e := p.BrowserData()
		if e != nil {
			return nil, e
		}
		data = append(data, d)
	}
	// JSON is emitted as the argument to JSON.parse, not a JS object literal:
	// fields such as __proto__ in passive extension data stay inert own properties.
	b, e := json.Marshal(data)
	if e != nil {
		return nil, e
	}
	quoted, e := json.Marshal(string(b))
	if e != nil {
		return nil, e
	}
	out := bytes.NewBufferString("// Generated by tools/cmd/knowledgeexport. Edit games/<slug>/knowledge.json.\n")
	out.WriteString("export const knowledgePackages = JSON.parse(")
	out.Write(quoted)
	out.WriteString(");\n")
	return out.Bytes(), nil
}
