#pragma once
#include "generated.cpp"
inline LocalDisc rrDisc;
inline uint32_t rrHash(const uint8_t*p,size_t n){uint32_t h=2166136261;for(size_t i=0;i<n;i++)h=(h^p[i])*16777619;return h;}
inline xbox_Machine*rrBoot(uint64_t n){rrDisc.mount(n);rrfiles::sources["disc.iso"]={n,[](uint64_t at,uint8_t*out,size_t n){rrDisc.read(at,out,n);return n;}};auto[d,de]=xbox_Open("disc.iso");if(de)throw std::runtime_error(de.text);auto[b,be]=xbox_Image_ReadFile(d,"default.xbe");if(be)throw std::runtime_error(be.text);auto[x,xe]=xbox_ParseXBE(b);if(xe)throw std::runtime_error(xe.text);auto[m,me]=xbox_NewMachine(x,d);if(me)throw std::runtime_error(me.text);xbox_Machine_EnableGPU(m);xbox_Machine_AttachPad(m,0);return m;}
struct RRSurface{uint32_t base{},pitch{};int w{640},h{480},ax{1},ay{1},sw{},sh{};bool valid{};};
inline RRSurface rrSurface(xbox_Machine*m){RRSurface s;auto*g=m->pgraph;auto&p=g->presented;uint32_t base;if(p.valid){base=p.base;s.pitch=p.pitch;s.w=p.w;s.h=p.h;s.ax=p.ax;s.ay=p.ay;}else{base=g->Regs[0x210/4];s.pitch=g->Regs[0x20c/4]&65535;s.w=g->Regs[0x200/4]>>16;s.h=g->Regs[0x204/4]>>16;auto[a,b]=xbox_surfaceAAScale(g->Regs[0x208/4]);s.ax=a;s.ay=b;if((g->Regs[0x208/4]>>8&15)==2){auto[w,h,e]=xbox_swizzleGeom(g->Regs[0x208/4]);if(e.empty()){s.sw=w;s.sh=h;}}}auto[a,mmio,ok]=xbox_Machine_translate(m,base);s.base=a;s.valid=ok&&!mmio&&s.w>0&&s.h>0&&s.w<=1280&&s.h<=1024&&(s.pitch||s.sw);if(!s.valid){s.w=640;s.h=480;}return s;}
inline uint32_t rrAddress(const RRSurface&s,int x,int y,int sx=0,int sy=0){if(!s.valid||x<0||y<0||x>=s.w||y>=s.h)return UINT32_MAX;if(s.sw)return s.base+xbox_swizzleOffset(x,y,s.sw,s.sh)*4;return s.base+(y*s.ay+sy)*s.pitch+(x*s.ax+sx)*4;}
inline std::vector<uint8_t>rrFrame(const uint8_t*b,size_t n,const RRSurface&s){std::vector<uint8_t>out(s.w*s.h*4);for(int y=0;y<s.h;y++)for(int x=0;x<s.w;x++){unsigned rgb[3]{};for(int sy=0;sy<s.ay;sy++)for(int sx=0;sx<s.ax;sx++){auto a=rrAddress(s,x,y,sx,sy);if(uint64_t(a)+4>n)continue;for(int j=0;j<3;j++)rgb[j]+=b[a+2-j];}auto i=(y*s.w+x)*4;for(int j=0;j<3;j++)out[i+j]=rgb[j]/(s.ax*s.ay);out[i+3]=255;}return out;}
inline auto rrFrame(xbox_Machine*m){return rrFrame(m->RAM.p,m->RAM.n,rrSurface(m));}
