#!/usr/bin/env python3
"""Generate explicit field lists from translated records; omitted fields are reviewed here."""
import re
from pathlib import Path
root=Path(__file__).resolve().parents[3]
skip={
 'allegrex_CPU':{'bus'},'psp_Machine':{'ram','vol','prof','Profile','GeLists','Log','logSeen'},'psp_Volume':{'src'},'psp_Image':{'closer'},
 'n64_Machine':{'ROM'},'r4300_CPU':{'bus','fetch'},'rsp_CPU':{'regs','DMEM','IMEM'},
 'threedo_diskStream':{'data'}, 'threedo_CvidMovie':{'Frames'},
 'arm_CPU':{'bus','wide'}, 'nds_ROM':{'Data'}, 'dsmachine_card':{'rom'}, 'dsmachine_vram':{'pages'},
 'n3ds_Machine':{'romfs','romfsRaw','pages','prof'}, 'n3ds_fsFile':{'data'},
 'arm60_CPU':{'bus','SWI'},'threedo_Volume':{'img'},
}
for platform in ['n64','threedo','nds','n3ds','psp']:
 source=(root/f'tools/platform/{platform}/browser/core/generated.cpp').read_text()
 records=[]
 for start in re.finditer(r'struct (\w+)\s*\{',source):
  depth=1;i=start.end()
  while depth:
   depth+=(source[i]=='{')-(source[i]=='}');i+=1
  records.append((start[1],source[start.end():i-1]))
 # Empty {} initializers contain no semicolon and are safe in this record grammar.
 out=['// Generated by tools/browser/state/generate.py. Explicit format v1 fields.','#pragma once','#include "../../../../browser/state/translated.h"']
 for match in records:
  name,body=match
  if platform=='psp' and name.startswith('Anon'):continue
  if '(' in body.replace('std::function','FUNCTION'): # callbacks excluded below, not a record exclusion
   pass
  fields=[]
  for field in body.split(';'):
   field=field.strip()
   if not field:continue
   if 'std::function' in field:continue
   m=re.search(r'(\w+)\s*(?:\{\})?$',field)
   if not m:raise Exception((name,field))
   if platform=='n3ds' and (m[1] in {'Census','workers','texCache','dec','decEpoch','shEpoch','decodedAll','prof'}):continue
   if name.startswith('Anon') and platform=='n3ds':continue
   if m[1] not in skip.get(name,set()):fields.append('v.'+m[1])
  tail=''
  if platform=='nds' and name=='dsmachine_core':
   fields.remove('v.wfi')
   tail='if(!a.reading||rrDSStateVersion>=2)a(v.wfi);'
  if platform=='nds' and name in {'dsmachine_geom','dsmachine_raster'}:
   extra='v.manualSort' if name=='dsmachine_geom' else 'v.transID'
   fields.remove(extra)
   tail+='if(!a.reading||rrDSStateVersion>=3)a('+extra+');'
  out.append(f'inline void stateFields(rrstate::Archive&a,{name}&v){{a('+','.join(fields)+');'+tail+'}')
 (root/f'tools/platform/{platform}/browser/core/state-fields.h').write_text('\n'.join(out)+'\n')
