#!/usr/bin/env python3
"""Generate explicit field lists from translated records; omitted fields are reviewed here."""
import re
from pathlib import Path
root=Path(__file__).resolve().parents[3]
skip={
 'n64_Machine':{'ROM'},'r4300_CPU':{'bus','fetch'},'rsp_CPU':{'regs','DMEM','IMEM'},
 'threedo_diskStream':{'data'}, 'threedo_CvidMovie':{'Frames'},
 'arm60_CPU':{'bus','SWI'},'threedo_Volume':{'img'},
}
for platform in ['n64','threedo']:
 source=(root/f'tools/platform/{platform}/browser/core/generated.cpp').read_text()
 records=[]
 for start in re.finditer(r'struct (\w+)\s*\{',source):
  depth=1;i=start.end()
  while depth:
   depth+=(source[i]=='{')-(source[i]=='}');i+=1
  records.append((start[1],source[start.end():i-1]))
 # Empty {} initializers contain no semicolon and are safe in this record grammar.
 out=['// Generated by tools/browser/state/generate.py. Explicit format v1 fields.','#pragma once','#include "../../../../browser/state/translated.h"']
 for match in records:
  name,body=match
  if '(' in body.replace('std::function','FUNCTION'): # callbacks excluded below, not a record exclusion
   pass
  fields=[]
  for field in body.split(';'):
   field=field.strip()
   if not field:continue
   if 'std::function' in field:continue
   m=re.search(r'(\w+)\s*(?:\{\})?$',field)
   if not m:raise Exception((name,field))
   if m[1] not in skip.get(name,set()):fields.append('v.'+m[1])
  out.append(f'inline void stateFields(rrstate::Archive&a,{name}&v){{a('+','.join(fields)+');}')
 (root/f'tools/platform/{platform}/browser/core/state-fields.h').write_text('\n'.join(out)+'\n')
