#include "../../platform/xbox/browser/core/api.cpp"
#include <cassert>
#include <iostream>
int main(){machine=arenaNew(xbox_Machine{});auto*m=machine;m->RAM=Slice<uint8_t>::make(64*1024*1024);m->CPU=x86_NewCPU(m);m->CPU->Mode=1;m->pgraph=xbox_newPgraph(m);xbox_Machine_EnableGPU(m);auto*g=m->pgraph;
 auto kv=[&](uint32_t a,uint32_t b){xbox_pgraph_kelvinMethod(g,a,b);};auto bits=[](float v){return std::bit_cast<uint32_t>(v);};kv(xbox_kelvinProgLoad,0);
 for(unsigned input:{0u,3u})for(auto w:std::array<uint32_t,4>{0,(1u<<21)|(input<<9)|0x1b,(2u<<26)|(0x1bu<<17)|(2u<<11)|(0x1bu<<2),(2u<<28)|(15u<<12)|(1u<<11)|(input==3?25u:0u)})kv(xbox_kelvinProgData,w);
 kv(xbox_kelvinProgStart,0);kv(xbox_kelvinTransformExecMode,6);kv(xbox_kelvinSurfaceFormat,0x128);kv(xbox_kelvinSurfacePitch,0x1000100);kv(xbox_kelvinSurfaceColorOffset,0x100000);kv(xbox_kelvinSurfaceZetaOffset,0x180000);kv(xbox_kelvinSurfaceClipH,64<<16);kv(xbox_kelvinSurfaceClipV,64<<16);kv(xbox_kelvinColorMask,0x01010101);
 kv(xbox_kelvinCombinerControl,1);kv(xbox_kelvinCombinerColorICW,0x04200000);kv(xbox_kelvinCombinerAlphaICW,0x14300000);kv(xbox_kelvinCombinerColorOCW,0xc00);kv(xbox_kelvinCombinerAlphaOCW,0xc00);kv(xbox_kelvinSpecFogCW0,12);kv(xbox_kelvinSpecFogCW1,0x1c00);
 for(unsigned i=0;i<16;i++)kv(xbox_kelvinVtxArrayFormat+4*i,2);kv(xbox_kelvinVtxArrayFormat,0x42);kv(xbox_kelvinVtxArrayFormat+12,0x40);
 assert(rr_capture_begin());kv(xbox_kelvinBeginEnd,xbox_primTriangles);for(auto xy:std::array<std::array<float,2>,3>{{{0,0},{60,0},{0,60}}})for(auto w:std::array<uint32_t,5>{bits(xy[0]),bits(xy[1]),0,bits(1),0xff00ff00})kv(xbox_kelvinInlineArray,w);kv(xbox_kelvinBeginEnd,0);assert(!m->CPU->Halted);assert(rr_capture_end());auto f=rrFrame(m);assert(f[(10*64+10)*4+1]==255);assert(f[(55*64+55)*4+1]==0);assert(rrcapture::trace.shadow==rrcapture::trace.final);assert(!rrcapture::trace.overflow);assert(std::string(rr_pixel(10,10)).find("complete\":true")!=std::string::npos);rr_replay_begin();while(!rr_replay_seek(rrreplay::replay.steps.size())){}assert(!memcmp(f.data(),rr_replay_frame(),f.size()));while(!rr_replay_seek(0)){}assert(memcmp(f.data(),rr_replay_frame(),f.size()));
 // Resume/suspend closures must retain the ordinal copied from the outer scope.
 auto*t=arenaNew(xbox_thread{});t->suspendCount=2;m->threads=append(m->threads,t);m->current=t;auto*o=arenaNew(xbox_kobject{});o->kind="thread";o->thread=t;m->objects[0x200]=o;m->CPU->Regs[4]=0x300;xbox_Machine_write32(m,0x304,0x200);xbox_Machine_write32(m,0x308,0x400);assert(xbox_kernelObjectHandler(224)(m)==2);assert(t->suspendCount==1&&xbox_Machine_read32(m,0x400)==2);xbox_kernelObjectHandler(231)(m);assert(t->suspendCount==2&&xbox_Machine_read32(m,0x400)==1);
 auto*h=go_sha1_New();h->update((const uint8_t*)"a",1);xbox_Machine_shaStore(m,123,h);h=xbox_Machine_shaLoad(m,123);h->update((const uint8_t*)"bc",2);auto digest=h->sum();const uint8_t expected[]={0xa9,0x99,0x3e,0x36,0x47,0x06,0x81,0x6a,0xba,0x3e,0x25,0x71,0x78,0x50,0xc2,0x6c,0x9c,0xd0,0xd8,0x9d};assert(!memcmp(digest.data(),expected,20));
 auto proof=std::string(rr_proof());auto n=rr_state_save();assert(n);auto b=stateOutput;m->RAM[123]=7;memcpy(rr_state_input(n),b.data(),n);assert(rr_state_load(n));assert(proof==rr_proof());assert(machine->current==machine->threads[0]&&get(machine->objects,0x200u)->thread==machine->current);memcpy(rr_state_input(n-1),b.data(),n-1);assert(!rr_state_load(n-1));assert(proof==rr_proof());
 for(int i=0;i<1000;i++){auto*img=rrTextureNew({1,1,false,Slice<uint8_t>::make(4),{}});auto*entry=rrTextureEntryNew({img,0,4,0});machine->pgraph->texCache[xbox_texKey{}]=entry;rrCollectTextures(machine->pgraph);}assert(rrTextures.size()==1&&rrTextureEntries.size()==1);
 std::cout<<"Xbox NV2A triangle/provenance/replay, thread closures, SHA1 continuation, state aliases and bounded texture ownership pass\n";
}
