import assert from 'node:assert/strict';
import {decodeStateType,createStateSampler,resolveStateLocation} from '../../../site/emulators/structured-state.js';
const types={u8:{kind:'integer',bytes:1,endian:'little'},i16:{kind:'integer',bytes:2,signed:true,endian:'little'},u64:{kind:'integer',bytes:8,endian:'big'},ship:{kind:'enum',storage:'u8',values:{1:'Ship'}},flags:{kind:'bitfield',storage:'u8',bits:{active:{offset:0,width:1,label:'Active'},mode:{offset:2,width:2,label:'Mode'}}},fixed:{kind:'fixed',storage:'i16',fractionBits:8},slot:{kind:'struct',size:4,fields:[{name:'type',offset:0,type:'ship'},{name:'flags',offset:1,type:'flags'},{name:'position',offset:2,type:'i16'}]},slots:{kind:'array',element:'slot',stride:5,count:2}};
assert.equal(decodeStateType(types,'u64',Array(8).fill(255)).value,'18446744073709551615');
assert.equal(decodeStateType(types,'i16',[0,128]).value,'-32768');
assert.equal(decodeStateType(types,'fixed',[128,254]).value,'-1.5');
assert.equal(decodeStateType(types,'fixed',[1,0]).value,'0.00390625');
assert.equal(decodeStateType(types,'ship',[99]).status,'unknown');
assert.equal(decodeStateType(types,'ship',[null]).status,'unavailable');
assert.deepEqual(decodeStateType(types,'flags',[13]).children.map(c=>c.value),['1','3']);
const partial=decodeStateType(types,'slot',[1,null,0,128]);assert.equal(partial.children[0].label,'type');assert.equal(partial.children[0].status,'known');assert.equal(partial.children[1].status,'unavailable');assert.equal(partial.children[2].value,'-32768');
assert.throws(()=>decodeStateType({...types,tooMany:{kind:'array',element:'u8',stride:1,count:257}},'tooMany',Array(257).fill(0)),/slot budget/);
assert.throws(()=>decodeStateType(types,'slots',Array(10).fill(0),{budget:{nodes:1}}),/node/);
let bytes=[0,13,0,0,0,99,0,0,128,0];
const knowledge={releaseId:'test',data:{types,spaces:{cpu:{kind:'cpu'}},locations:{base:{kind:'cpu',space:'cpu',address:'0x800'},relative:{kind:'relative',base:'base',offset:'0x10'}},evidence:{test:{status:'verified',description:'Synthetic'}},state:{slots:{label:'Synthetic slots',type:'slots',location:'base',releases:['test'],evidence:['test'],applicability:'Synthetic fixture only',occupancy:{path:['type'],notEquals:'0'}}}}};
assert.equal(resolveStateLocation(knowledge.data,'relative').address,0x810);
const sample=createStateSampler(knowledge,()=>({bytes:[...bytes],mapping:Array(10).fill(0)}));
const context={cycle:'100',boundary:true};let result=sample(context),slots=result.entries[0].node.children;
assert.equal(result.cycle,'100');assert.equal(slots[0].occupancy,'empty');assert.equal(slots[1].occupancy,'occupied');assert.equal(slots[1].children[0].status,'unknown');assert.equal(slots[1].incarnation,1);assert.equal(slots[1].offset,5);
bytes[5]=0;assert.equal(sample(context).entries[0].node.children[1].occupancy,'empty');bytes[5]=1;assert.equal(sample(context).entries[0].node.children[1].incarnation,2);
bytes[5]=null;assert.equal(sample(context).entries[0].node.children[1].occupancy,'unavailable');bytes[5]=1;assert.equal(sample(context).entries[0].node.children[1].incarnation,3);
assert.deepEqual(createStateSampler(null,()=>{throw Error('must not read')})(context).entries,[]);
console.log('PASS M3 structured state: endian/signed/64-bit/fixed/bitfields, partial reads, unknown enums, arrays/records, occupancy/reuse, locations and budgets');
