#!/usr/bin/env python3
"""Reuse owned metadata; no third-party CPU implementation is compiled."""
import argparse
from pathlib import Path
from instruction_set import opcodes
ops=opcodes()
lines=['// Generated by generate-opcodes.py from RetroReverse opcode metadata.','#include "cpu.h"','namespace rr::c64 {','const Instruction instructions[256] = {']
for code in range(256):
 name,mode=ops.get(code,('Unknown','imp'))
 lines.append(' {Op::%s,Mode::%s}, // %02X'%(name,mode,code))
lines+=['};','}']
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
output=Path(__file__).with_name('opcodes.cpp');generated='\n'.join(lines)+'\n'
if args.check:
 if output.read_text()!=generated:raise SystemExit('Owned CPU opcode metadata is stale; run generate-opcodes.py')
else:output.write_text(generated)
