#!/usr/bin/env python3
"""Reuse RetroReverse's documented instruction metadata; no third-party CPU code."""
import argparse,json
from pathlib import Path
root=Path(__file__).resolve().parents[4]
text=(root/'site/emulators/opcodes6502.js').read_text()
ops=json.loads(text.split('export const opcodes = ',1)[1].strip().removesuffix(';'))
lines=['// Generated by generate-opcodes.py from RetroReverse opcode metadata.','#include "cpu.h"','namespace rr::c64 {','const Instruction instructions[256] = {']
for code in range(256):
 op=ops.get(str(code),{'mnemonic':'Unknown','mode':'imp'})
 lines.append(' {Op::%s,Mode::%s}, // %02X'%(op['mnemonic'],op['mode'],code))
lines+=['};','}']
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
output=Path(__file__).with_name('opcodes.cpp');generated='\n'.join(lines)+'\n'
if args.check:
 if output.read_text()!=generated:raise SystemExit('Owned CPU opcode metadata is stale; run generate-opcodes.py')
else:output.write_text(generated)
