; ============================================================================
; uw.asm — Ultima Underworld (UW.EXE) C-runtime startup, code-traced
; ============================================================================
;
; Generated by the repository's own x86 code-tracer from the DOS entry point,
; then reduced to the reachable code (the intervening data spans are dropped;
; this is the resident Microsoft-C startup, not the whole 549 KB image):
;
;   go run retroreverse.com/tools/cmd/codetracex86 \
;       -skip 0x3200 -base 0 -entry EC50 \
;       -o "Ultima Underworld (PC)/disasm/uw.raw.asm" \
;       "Ultima Underworld (PC)/game/UW.EXE"
;
; Addresses are module offsets (load segment 0, i.e. file offset minus the
; 0x3200 MZ header). The trace reaches 10 routines / 1011 bytes and then stops
; at the C-runtime's indirect handoff into the game proper — the game's own
; startup runs in overlay-paged and relocated segments whose file bytes differ
; from their run-time content, so it cannot be traced statically. Those routines
; are documented, with the addresses the execution-core oracle pinned at run
; time, in uw.annotations.txt.
;
; See ../Ultima_Underworld.md Part II §3 and Part III for the narrative.
; ============================================================================

00EC50  BA 0F 5C                      MOV DX, $5C0F
00EC53  2E 89 16 3C 02                MOV [CS:$023C], DX
00EC58  B4 30                         MOV AH, $30
00EC5A  CD 21                         INT $21
00EC5C  8B 2E 02 00                   MOV BP, [$0002]
00EC60  8B 1E 2C 00                   MOV BX, [$002C]
00EC64  8E DA                         MOV DS, DX
00EC66  A3 90 00                      MOV [$0090], AX
00EC69  8C 06 8E 00                   MOV [$008E], ES
00EC6D  89 1E 8A 00                   MOV [$008A], BX
00EC71  89 2E A6 00                   MOV [$00A6], BP
00EC75  E8 43 01                      CALL $0000EDBB
00EC78  C4 3E 88 00                   LES DI, [$0088]
00EC7C  8B C7                         MOV AX, DI
00EC7E  8B D8                         MOV BX, AX
00EC80  B9 FF 7F                      MOV CX, $7FFF
00EC83  FC                            CLD
00EC84  F2 AE                         REPNE SCASB
00EC86  E3 61                         JCXZ $0000ECE9
00EC88  43                            INC BX
00EC89  26 38 05                      CMP [ES:DI], AL
00EC8C  75 F6                         JNZ $0000EC84
00EC8E  80 CD 80                      OR CH, $80
00EC91  F7 D9                         NEG CX
00EC93  89 0E 88 00                   MOV [$0088], CX
00EC97  B9 01 00                      MOV CX, $0001
00EC9A  D3 E3                         SHL BX, CL
00EC9C  83 C3 08                      ADD BX, $0008
00EC9F  83 E3 F8                      AND BX, $FFF8
00ECA2  89 1E 8C 00                   MOV [$008C], BX
00ECA6  8C DA                         MOV DX, DS
00ECA8  2B EA                         SUB BP, DX
00ECAA  8B 3E 3C 12                   MOV DI, [$123C]
00ECAE  81 FF 00 02                   CMP DI, $0200
00ECB2  73 07                         JNB $0000ECBB
00ECB4  BF 00 02                      MOV DI, $0200
00ECB7  89 3E 3C 12                   MOV [$123C], DI
00ECBB  81 C7 B4 77                   ADD DI, $77B4
00ECBF  72 28                         JB $0000ECE9
00ECC1  03 3E 3A 12                   ADD DI, [$123A]
00ECC5  72 22                         JB $0000ECE9
00ECC7  B1 04                         MOV CL, $04
00ECC9  D3 EF                         SHR DI, CL
00ECCB  47                            INC DI
00ECCC  3B EF                         CMP BP, DI
00ECCE  72 19                         JB $0000ECE9
00ECD0  83 3E 3C 12 00                CMP WORD [$123C], $0000
00ECD5  74 07                         JZ $0000ECDE
00ECD7  83 3E 3A 12 00                CMP WORD [$123A], $0000
00ECDC  75 0E                         JNZ $0000ECEC
00ECDE  BF 00 10                      MOV DI, $1000
00ECE1  3B EF                         CMP BP, DI
00ECE3  77 07                         JA $0000ECEC
00ECE5  8B FD                         MOV DI, BP
00ECE7  EB 03                         JMP $0000ECEC
00ECE9  E9 8A 01                      JMP $0000EE76
00ECEC  8B DF                         MOV BX, DI
00ECEE  03 DA                         ADD BX, DX
00ECF0  89 1E 9E 00                   MOV [$009E], BX
00ECF4  89 1E A2 00                   MOV [$00A2], BX
00ECF8  A1 8E 00                      MOV AX, [$008E]
00ECFB  2B D8                         SUB BX, AX
00ECFD  8E C0                         MOV ES, AX
00ECFF  B4 4A                         MOV AH, $4A
00ED01  57                            PUSH DI
00ED02  CD 21                         INT $21
00ED04  5F                            POP DI
00ED05  D3 E7                         SHL DI, CL
00ED07  FA                            CLI
00ED08  8E D2                         MOV SS, DX
00ED0A  8B E7                         MOV SP, DI
00ED0C  FB                            STI
00ED0D  33 C0                         XOR AX, AX
00ED0F  2E 8E 06 3C 02                MOV ES, [CS:$023C]
00ED14  BF 64 22                      MOV DI, $2264
00ED17  B9 B4 77                      MOV CX, $77B4
00ED1A  2B CF                         SUB CX, DI
00ED1C  FC                            CLD
00ED1D  F3 AA                         REP STOSB
00ED1F  B4 00                         MOV AH, $00
00ED21  CD 1A                         INT $1A
00ED23  89 16 94 00                   MOV [$0094], DX
00ED27  89 0E 96 00                   MOV [$0096], CX
00ED2B  33 ED                         XOR BP, BP
00ED2D  B8 B6 5A                      MOV AX, $5AB6
00ED30  8E D8                         MOV DS, AX
00ED32  BE 08 00                      MOV SI, $0008
00ED35  BF 20 00                      MOV DI, $0020
00ED38  E8 F0 00                      CALL $0000EE2B
00ED3B  2E 8E 1E 3C 02                MOV DS, [CS:$023C]
00ED40  2E C6 06 ED 01 72             MOV BYTE [CS:$01ED], $72
00ED46  2E C6 06 DC 01 00             MOV BYTE [CS:$01DC], $00
00ED4C  FF 36 86 00                   PUSH WORD [$0086]
00ED50  FF 36 84 00                   PUSH WORD [$0084]
00ED54  FF 36 82 00                   PUSH WORD [$0082]
00ED58  9A 43 00 3B 5B                CALLF $5B3B:$0043
00ED5D  50                            PUSH AX
00ED5E  9A 23 03 C5 0E                CALLF $0EC5:$0323

; ==== sub_00ED63 (1 caller) ====
00ED63  B8 B8 5A                      MOV AX, $5AB8
00ED66  8E D8                         MOV DS, AX
00ED68  BE 00 00                      MOV SI, $0000
00ED6B  BF 06 00                      MOV DI, $0006
00ED6E  E8 BA 00                      CALL $0000EE2B
00ED71  2E 8E 1E 3C 02                MOV DS, [CS:$023C]
00ED76  FF 1E 32 1D                   CALLF WORD [$1D32]
00ED7A  FF 1E 36 1D                   CALLF WORD [$1D36]
00ED7E  FF 1E 3A 1D                   CALLF WORD [$1D3A]
00ED82  50                            PUSH AX

; ==== sub_00ED83 (1 caller) ====
00ED83  2E 8E 1E 3C 02                MOV DS, [CS:$023C]
00ED88  0E                            PUSH CS
00ED89  E8 72 00                      CALL $0000EDFE
00ED8C  33 C0                         XOR AX, AX
00ED8E  8B F0                         MOV SI, AX
00ED90  B9 2D 00                      MOV CX, $002D
00ED93  02 04                         ADD AL, [SI]
00ED95  80 D4 00                      ADC AH, $00
00ED98  46                            INC SI
00ED99  E2 F8                         LOOP $0000ED93
00ED9B  2D A5 0C                      SUB AX, $0CA5
00ED9E  74 09                         JZ $0000EDA9
00EDA0  B9 19 00                      MOV CX, $0019
00EDA3  BA 2D 00                      MOV DX, $002D
00EDA6  E8 C5 00                      CALL $0000EE6E
00EDA9  8B EC                         MOV BP, SP
00EDAB  B4 4C                         MOV AH, $4C
00EDAD  8A 46 04                      MOV AL, [BP+$4]
00EDB0  CD 21                         INT $21
00EDB2  B9 0E 00                      MOV CX, $000E
00EDB5  BA 46 00                      MOV DX, $0046
00EDB8  E9 C1 00                      JMP $0000EE7C

; ==== sub_00EDBB (1 caller) ====
00EDBB  1E                            PUSH DS
00EDBC  B8 00 35                      MOV AX, $3500
00EDBF  CD 21                         INT $21
00EDC1  89 1E 72 00                   MOV [$0072], BX
00EDC5  8C 06 74 00                   MOV [$0074], ES
00EDC9  B8 04 35                      MOV AX, $3504
00EDCC  CD 21                         INT $21
00EDCE  89 1E 76 00                   MOV [$0076], BX
00EDD2  8C 06 78 00                   MOV [$0078], ES
00EDD6  B8 05 35                      MOV AX, $3505
00EDD9  CD 21                         INT $21
00EDDB  89 1E 7A 00                   MOV [$007A], BX
00EDDF  8C 06 7C 00                   MOV [$007C], ES
00EDE3  B8 06 35                      MOV AX, $3506
00EDE6  CD 21                         INT $21
00EDE8  89 1E 7E 00                   MOV [$007E], BX
00EDEC  8C 06 80 00                   MOV [$0080], ES
00EDF0  B8 00 25                      MOV AX, $2500
00EDF3  8C CA                         MOV DX, CS
00EDF5  8E DA                         MOV DS, DX
00EDF7  BA 62 01                      MOV DX, $0162
00EDFA  CD 21                         INT $21
00EDFC  1F                            POP DS
00EDFD  C3                            RET

; ==== sub_00EDFE (1 caller) ====
00EDFE  1E                            PUSH DS
00EDFF  B8 00 25                      MOV AX, $2500
00EE02  C5 16 72 00                   LDS DX, [$0072]
00EE06  CD 21                         INT $21
00EE08  1F                            POP DS
00EE09  1E                            PUSH DS
00EE0A  B8 04 25                      MOV AX, $2504
00EE0D  C5 16 76 00                   LDS DX, [$0076]
00EE11  CD 21                         INT $21
00EE13  1F                            POP DS
00EE14  1E                            PUSH DS
00EE15  B8 05 25                      MOV AX, $2505
00EE18  C5 16 7A 00                   LDS DX, [$007A]
00EE1C  CD 21                         INT $21
00EE1E  1F                            POP DS
00EE1F  1E                            PUSH DS
00EE20  B8 06 25                      MOV AX, $2506
00EE23  C5 16 7E 00                   LDS DX, [$007E]
00EE27  CD 21                         INT $21
00EE29  1F                            POP DS
00EE2A  CB                            RETF

; ==== sub_00EE2B (2 callers) ====
00EE2B  B4 FF                         MOV AH, $FF
00EE2D  8B D7                         MOV DX, DI
00EE2F  8B DE                         MOV BX, SI
00EE31  3B DF                         CMP BX, DI
00EE33  74 14                         JZ $0000EE49
00EE35  80 3F FF                      CMP BYTE [BX], $FF
00EE38  74 0A                         JZ $0000EE44
00EE3A  38 67 01                      CMP [BX+$1], AH
00EE3D  77 05                         JA $0000EE44
00EE3F  8A 67 01                      MOV AH, [BX+$1]
00EE42  8B D3                         MOV DX, BX
00EE44  83 C3 06                      ADD BX, $0006
00EE47  EB E8                         JMP $0000EE31
00EE49  3B D7                         CMP DX, DI
00EE4B  74 20                         JZ $0000EE6D
00EE4D  8B DA                         MOV BX, DX
00EE4F  1E                            PUSH DS
00EE50  07                            POP ES
00EE51  06                            PUSH ES
00EE52  80 3F 00                      CMP BYTE [BX], $00
00EE55  C6 07 FF                      MOV BYTE [BX], $FF
00EE58  2E 8E 1E 3C 02                MOV DS, [CS:$023C]
00EE5D  74 07                         JZ $0000EE66
00EE5F  26 FF 5F 02                   CALLF WORD [ES:BX+$2]
00EE63  1F                            POP DS
00EE64  EB C5                         JMP $0000EE2B
00EE66  26 FF 57 02                   CALL [ES:BX+$2]
00EE6A  1F                            POP DS
00EE6B  EB BE                         JMP $0000EE2B
00EE6D  C3                            RET

; ==== sub_00EE6E (2 callers) ====
00EE6E  B4 40                         MOV AH, $40
00EE70  BB 02 00                      MOV BX, $0002
00EE73  CD 21                         INT $21
00EE75  C3                            RET
00EE76  B9 1E 00                      MOV CX, $001E
00EE79  BA 54 00                      MOV DX, $0054
00EE7C  2E 8E 1E 3C 02                MOV DS, [CS:$023C]
00EE81  E8 EA FF                      CALL $0000EE6E
00EE84  B8 03 00                      MOV AX, $0003
00EE87  50                            PUSH AX
00EE88  0E                            PUSH CS
00EE89  E8 F7 FE                      CALL $0000ED83
00EE8C  00 00                         ADD [BX+SI], AL
00EE8E  02 80 55 8B                   ADD AL, [BX+SI-$74AB]
00EE92  EC                            IN AL, DX
00EE93  56                            PUSH SI
00EE94  33 C0                         XOR AX, AX
00EE96  50                            PUSH AX
00EE97  FF 76 06                      PUSH WORD [BP+$6]
00EE9A  9A BA 16 C5 0E                CALLF $0EC5:$16BA
00EE9F  59                            POP CX
00EEA0  59                            POP CX
00EEA1  8B F0                         MOV SI, AX
00EEA3  83 FE FF                      CMP SI, $FFFF
00EEA6  75 02                         JNZ $0000EEAA
00EEA8  EB 1A                         JMP $0000EEC4
00EEAA  F7 46 08 02 00                TEST WORD [BP+$8], $0002
00EEAF  74 06                         JZ $0000EEB7
00EEB1  F7 C6 01 00                   TEST SI, $0001
00EEB5  75 04                         JNZ $0000EEBB
00EEB7  33 C0                         XOR AX, AX
00EEB9  EB 09                         JMP $0000EEC4
00EEBB  C7 06 92 00 05 00             MOV WORD [$0092], $0005
00EEC1  B8 FF FF                      MOV AX, $FFFF
00EEC4  5E                            POP SI
00EEC5  5D                            POP BP
00EEC6  CB                            RETF

; ==== sub_00EF73 (1 caller) ====
00EF73  55                            PUSH BP
00EF74  8B EC                         MOV BP, SP
00EF76  EB 0C                         JMP $0000EF84
00EF78  8B 1E 2E 1C                   MOV BX, [$1C2E]
00EF7C  D1 E3                         SHL BX, 1
00EF7E  D1 E3                         SHL BX, 1
00EF80  FF 9F 8C 71                   CALLF WORD [BX+$718C]
00EF84  A1 2E 1C                      MOV AX, [$1C2E]
00EF87  FF 0E 2E 1C                   DEC WORD [$1C2E]
00EF8B  0B C0                         OR AX, AX
00EF8D  75 E9                         JNZ $0000EF78
00EF8F  FF 76 06                      PUSH WORD [BP+$6]
00EF92  E8 CE FD                      CALL $0000ED63
00EF95  59                            POP CX
00EF96  5D                            POP BP
00EF97  CB                            RETF

; ==== sub_01030A (1 caller) ====
01030A  55                            PUSH BP
01030B  8B EC                         MOV BP, SP
01030D  8B 4E 0A                      MOV CX, [BP+$A]
010310  B4 43                         MOV AH, $43
010312  8A 46 08                      MOV AL, [BP+$8]
010315  8B 56 06                      MOV DX, [BP+$6]
010318  CD 21                         INT $21
01031A  72 03                         JB $0001031F
01031C  91                            XCHG AX, CX
01031D  EB 04                         JMP $00010323
01031F  50                            PUSH AX
010320  E8 28 06                      CALL $0001094B
010323  5D                            POP BP
010324  CB                            RETF

; ==== sub_01094B (1 caller) ====
01094B  55                            PUSH BP
01094C  8B EC                         MOV BP, SP
01094E  56                            PUSH SI
01094F  8B 76 04                      MOV SI, [BP+$4]
010952  0B F6                         OR SI, SI
010954  7C 15                         JL $0001096B
010956  83 FE 58                      CMP SI, $0058
010959  7E 03                         JLE $0001095E
01095B  BE 57 00                      MOV SI, $0057
01095E  89 36 CC 1E                   MOV [$1ECC], SI
010962  8A 84 CE 1E                   MOV AL, [SI+$1ECE]
010966  98                            CBW
010967  8B F0                         MOV SI, AX
010969  EB 11                         JMP $0001097C
01096B  8B C6                         MOV AX, SI
01096D  F7 D8                         NEG AX
01096F  8B F0                         MOV SI, AX
010971  83 FE 23                      CMP SI, $0023
010974  7F E5                         JG $0001095B
010976  C7 06 CC 1E FF FF             MOV WORD [$1ECC], $FFFF
01097C  89 36 92 00                   MOV [$0092], SI
010980  B8 FF FF                      MOV AX, $FFFF
010983  5E                            POP SI
010984  5D                            POP BP
010985  C2 02 00                      RET $0002

; ==== sub_05B3F3 (1 caller) ====
05B3F3  CD 3F                         INT $3F
05B3F5  00 00                         ADD [BX+SI], AL
05B3F7  00 CD                         ADD CH, CL
05B3F9  3F                            AAS
05B3FA  28 03                         SUB [BP+DI], AL
05B3FC  00 CD                         ADD CH, CL
05B3FE  3F                            AAS
05B3FF  B8 03 00                      MOV AX, $0003
05B402  CD 3F                         INT $3F
05B404  EB 01                         JMP $0005B407
05B407  CD 3F                         INT $3F
05B409  A0 03 00                      MOV AL, [$0003]
05B40C  CD 3F                         INT $3F
05B40E  D4 02                         AAM $02
05B410  00 CD                         ADD CH, CL
05B412  3F                            AAS
05B413  8C 04                         MOV [SI], ES
05B415  00 CD                         ADD CH, CL
05B417  3F                            AAS
05B418  5B                            POP BX
05B419  05 00 CD                      ADD AX, $CD00
05B41C  3F                            AAS
05B41D  51                            PUSH CX
05B41E  06                            PUSH ES
05B41F  00 CD                         ADD CH, CL
05B421  3F                            AAS
05B422  0F 02 00                      LAR AX, [BX+SI]
05B425  00 00                         ADD [BX+SI], AL
05B427  00 00                         ADD [BX+SI], AL
05B429  00 00                         ADD [BX+SI], AL
05B42B  00 00                         ADD [BX+SI], AL
05B42D  00 00                         ADD [BX+SI], AL
05B42F  00 CD                         ADD CH, CL
05B431  3F                            AAS
05B432  00 00                         ADD [BX+SI], AL
05B434  C0 11 01                      RCL BYTE [BX+DI], $01
05B437  00 D7                         ADD BH, DL
05B439  01 2E 00 04                   ADD [$0400], BP
05B43D  00 00                         ADD [BX+SI], AL
05B43F  00 00                         ADD [BX+SI], AL
05B441  00 00                         ADD [BX+SI], AL
05B443  00 00                         ADD [BX+SI], AL
05B445  00 00                         ADD [BX+SI], AL
05B447  00 00                         ADD [BX+SI], AL
05B449  00 00                         ADD [BX+SI], AL
05B44B  00 00                         ADD [BX+SI], AL
05B44D  00 00                         ADD [BX+SI], AL
05B44F  00 CD                         ADD CH, CL
05B451  3F                            AAS
05B452  00 00                         ADD [BX+SI], AL
05B454  00 CD                         ADD CH, CL
05B456  3F                            AAS
05B457  F8                            CLC
05B458  00 00                         ADD [BX+SI], AL
05B45A  CD 3F                         INT $3F
05B45C  8E 01                         MOV ES, [BX+DI]
05B45E  00 CD                         ADD CH, CL
05B460  3F                            AAS
05B461  D3 00                         ROL WORD [BX+SI], CL
05B463  00 00                         ADD [BX+SI], AL
05B465  00 00                         ADD [BX+SI], AL
05B467  00 00                         ADD [BX+SI], AL
05B469  00 00                         ADD [BX+SI], AL
05B46B  00 00                         ADD [BX+SI], AL
05B46D  00 00                         ADD [BX+SI], AL
05B46F  00 CD                         ADD CH, CL
05B471  3F                            AAS
05B472  00 00                         ADD [BX+SI], AL
05B474  D0 13                         RCL BYTE [BP+DI], 1
05B476  01 00                         ADD [BX+SI], AX
05B478  00 00                         ADD [BX+SI], AL
05B47A  00 00                         ADD [BX+SI], AL
05B47C  00 00                         ADD [BX+SI], AL
05B47E  00 00                         ADD [BX+SI], AL
05B480  00 00                         ADD [BX+SI], AL
05B482  00 00                         ADD [BX+SI], AL
05B484  00 00                         ADD [BX+SI], AL
05B486  00 00                         ADD [BX+SI], AL
05B488  00 00                         ADD [BX+SI], AL
05B48A  00 00                         ADD [BX+SI], AL
05B48C  00 00                         ADD [BX+SI], AL
05B48E  00 00                         ADD [BX+SI], AL
05B490  CD 3F                         INT $3F
05B492  00 00                         ADD [BX+SI], AL
05B494  E0 13                         LOOPNE $0005B4A9
05B496  01 00                         ADD [BX+SI], AX
05B498  6E                            OUTSB
05B499  04 50                         ADD AL, $50
05B49B  00 06 00 00                   ADD [$0000], AL
05B49F  00 00                         ADD [BX+SI], AL
05B4A1  00 00                         ADD [BX+SI], AL
05B4A3  00 00                         ADD [BX+SI], AL
05B4A5  00 00                         ADD [BX+SI], AL
05B4A7  00 00                         ADD [BX+SI], AL
05B4A9  00 00                         ADD [BX+SI], AL
05B4AB  00 00                         ADD [BX+SI], AL
05B4AD  00 00                         ADD [BX+SI], AL
05B4AF  00 CD                         ADD CH, CL
05B4B1  3F                            AAS
05B4B2  00 00                         ADD [BX+SI], AL
05B4B4  00 CD                         ADD CH, CL
05B4B6  3F                            AAS
05B4B7  15 04 00                      ADC AX, $0004
05B4BA  CD 3F                         INT $3F
05B4BC  44                            INC SP
05B4BD  02 00                         ADD AL, [BX+SI]
05B4BF  CD 3F                         INT $3F
05B4C1  D7                            XLAT
05B4C2  01 00                         ADD [BX+SI], AX
05B4C4  CD 3F                         INT $3F
05B4C6  98                            CBW
05B4C7  03 00                         ADD AX, [BX+SI]
05B4C9  CD 3F                         INT $3F
05B4CB  D1 02                         ROL WORD [BP+SI], 1
05B4CD  00 00                         ADD [BX+SI], AL
05B4CF  00 CD                         ADD CH, CL
05B4D1  3F                            AAS
05B4D2  00 00                         ADD [BX+SI], AL
05B4D4  A0 18 01                      MOV AL, [$0118]
05B4D7  00 FF                         ADD BH, BH
05B4D9  05 9E 00                      ADD AX, $009E
05B4DC  11 00                         ADC [BX+SI], AX
05B4DE  00 00                         ADD [BX+SI], AL
05B4E0  00 00                         ADD [BX+SI], AL
05B4E2  00 00                         ADD [BX+SI], AL
05B4E4  00 00                         ADD [BX+SI], AL
05B4E6  00 00                         ADD [BX+SI], AL
05B4E8  00 00                         ADD [BX+SI], AL
05B4EA  00 00                         ADD [BX+SI], AL
05B4EC  00 00                         ADD [BX+SI], AL
05B4EE  00 00                         ADD [BX+SI], AL
05B4F0  CD 3F                         INT $3F
05B4F2  CF                            IRET
