#!/usr/bin/env python3
"""Derive a resumable Run from the generated Go translation, preserving all locals.
The original Run remains available as an independent whole-frame oracle.
Run after regenerating generated.cpp. No game-specific scheduling is introduced.
"""
from pathlib import Path
root=Path(__file__).resolve().parent
s=(root/'core/generated.cpp').read_text()
a=s.index('threedo_Result threedo_Machine_Run(threedo_Machine* m,uint64_t maxSteps){')
b=s.index('// tools/platform/',a)
s=s[a:b].replace('threedo_Machine_Run(threedo_Machine* m,uint64_t maxSteps)', 'threedo_Machine_RunSlice(threedo_Machine* m,uint64_t budget, RunContext& context)')
fields={'uint64_t steps={};':'auto& steps=context.steps; const auto initial=steps; const auto maxSteps=initial+budget;', 'Map<uint32_t,bool> seen = Map<uint32_t,bool>{};':'auto& seen=context.seen;', 'uint64_t sinceNew={};':'auto& sinceNew=context.sinceNew;', 'std::array<uint32_t,64> ring={};':'auto& ring=context.ring;', 'int64_t ri={};':'auto& ri=context.ri;', 'int64_t unstickTries={};':'auto& unstickTries=context.unstickTries;', 'int64_t stallSwitches={};':'auto& stallSwitches=context.stallSwitches;'}
for old,new in fields.items():
 assert old in s,old
 s=s.replace(old,new)
s=s.replace('threedo_Result{steps,','threedo_Result{steps-initial,')
s=s.replace('for (;(steps < maxSteps);){', 'for (;(steps < maxSteps);){\nif(m->MovieHLE && m->moviePos<m->movieQueue.n)return threedo_Result{steps-initial,m->CPU->R[15],"movie pending"};')
(root/'core/slice.h').write_text('''// Generated by ../slice.py. Scheduler locals survive browser yields.
#pragma once
struct RunContext {
 uint64_t steps=0,sinceNew=0;
 Map<uint32_t,bool> seen;
 std::array<uint32_t,64> ring{};
 int64_t ri=0,unstickTries=0,stallSwitches=0;
};
inline '''+s)
